# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_TempusAccess_dock_widget.ui'
#
# Created: Tue Apr 09 18:47:15 2019
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(667, 541)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(160)
        sizePolicy.setVerticalStretch(42)
        sizePolicy.setHeightForWidth(DockWidget.sizePolicy().hasHeightForWidth())
        DockWidget.setSizePolicy(sizePolicy)
        DockWidget.setBaseSize(QtCore.QSize(0, 0))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.Tabs = QtGui.QTabWidget(self.dockWidgetContents)
        self.Tabs.setEnabled(True)
        self.Tabs.setGeometry(QtCore.QRect(10, 0, 651, 471))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        self.Tabs.setAutoFillBackground(False)
        self.Tabs.setObjectName(_fromUtf8("Tabs"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBoxObjType = QtGui.QGroupBox(self.tab_5)
        self.groupBoxObjType.setEnabled(True)
        self.groupBoxObjType.setGeometry(QtCore.QRect(10, 10, 341, 61))
        self.groupBoxObjType.setObjectName(_fromUtf8("groupBoxObjType"))
        self.comboBoxObjType = QtGui.QComboBox(self.groupBoxObjType)
        self.comboBoxObjType.setGeometry(QtCore.QRect(20, 30, 311, 21))
        self.comboBoxObjType.setObjectName(_fromUtf8("comboBoxObjType"))
        self.groupBoxIndicators = QtGui.QGroupBox(self.tab_5)
        self.groupBoxIndicators.setGeometry(QtCore.QRect(360, 10, 271, 261))
        self.groupBoxIndicators.setObjectName(_fromUtf8("groupBoxIndicators"))
        self.listViewIndic = QtGui.QListView(self.groupBoxIndicators)
        self.listViewIndic.setEnabled(True)
        self.listViewIndic.setGeometry(QtCore.QRect(10, 30, 241, 191))
        self.listViewIndic.setMaximumSize(QtCore.QSize(16777215, 300))
        self.listViewIndic.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewIndic.setObjectName(_fromUtf8("listViewIndic"))
        self.layoutWidget = QtGui.QWidget(self.groupBoxIndicators)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 230, 241, 22))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelPerimeterType_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPerimeterType_2.sizePolicy().hasHeightForWidth())
        self.labelPerimeterType_2.setSizePolicy(sizePolicy)
        self.labelPerimeterType_2.setObjectName(_fromUtf8("labelPerimeterType_2"))
        self.horizontalLayout_2.addWidget(self.labelPerimeterType_2)
        self.comboBoxIndicZoning = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxIndicZoning.sizePolicy().hasHeightForWidth())
        self.comboBoxIndicZoning.setSizePolicy(sizePolicy)
        self.comboBoxIndicZoning.setObjectName(_fromUtf8("comboBoxIndicZoning"))
        self.horizontalLayout_2.addWidget(self.comboBoxIndicZoning)
        self.groupBoxPaths = QtGui.QGroupBox(self.tab_5)
        self.groupBoxPaths.setGeometry(QtCore.QRect(10, 80, 341, 361))
        self.groupBoxPaths.setObjectName(_fromUtf8("groupBoxPaths"))
        self.layoutWidget_5 = QtGui.QWidget(self.groupBoxPaths)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 30, 311, 22))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_33 = QtGui.QLabel(self.layoutWidget_5)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_9.addWidget(self.label_33)
        self.comboBoxNodeType = QtGui.QComboBox(self.layoutWidget_5)
        self.comboBoxNodeType.setObjectName(_fromUtf8("comboBoxNodeType"))
        self.horizontalLayout_9.addWidget(self.comboBoxNodeType)
        self.toolBoxPaths = QtGui.QToolBox(self.groupBoxPaths)
        self.toolBoxPaths.setEnabled(True)
        self.toolBoxPaths.setGeometry(QtCore.QRect(10, 100, 321, 251))
        self.toolBoxPaths.setObjectName(_fromUtf8("toolBoxPaths"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page.setObjectName(_fromUtf8("page"))
        self.layoutWidget_3 = QtGui.QWidget(self.page)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 0, 301, 95))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBoxDest = QtGui.QComboBox(self.layoutWidget_3)
        self.comboBoxDest.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDest.sizePolicy().hasHeightForWidth())
        self.comboBoxDest.setSizePolicy(sizePolicy)
        self.comboBoxDest.setObjectName(_fromUtf8("comboBoxDest"))
        self.gridLayout.addWidget(self.comboBoxDest, 2, 1, 1, 1)
        self.labelFromNode = QtGui.QLabel(self.layoutWidget_3)
        self.labelFromNode.setEnabled(True)
        self.labelFromNode.setObjectName(_fromUtf8("labelFromNode"))
        self.gridLayout.addWidget(self.labelFromNode, 0, 0, 1, 1)
        self.pushButtonChooseOrigOnMap = QtGui.QPushButton(self.layoutWidget_3)
        self.pushButtonChooseOrigOnMap.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChooseOrigOnMap.sizePolicy().hasHeightForWidth())
        self.pushButtonChooseOrigOnMap.setSizePolicy(sizePolicy)
        self.pushButtonChooseOrigOnMap.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonChooseOrigOnMap.setObjectName(_fromUtf8("pushButtonChooseOrigOnMap"))
        self.gridLayout.addWidget(self.pushButtonChooseOrigOnMap, 0, 2, 1, 1)
        self.labelToNode = QtGui.QLabel(self.layoutWidget_3)
        self.labelToNode.setEnabled(True)
        self.labelToNode.setObjectName(_fromUtf8("labelToNode"))
        self.gridLayout.addWidget(self.labelToNode, 2, 0, 1, 1)
        self.pushButtonChooseDestOnMap = QtGui.QPushButton(self.layoutWidget_3)
        self.pushButtonChooseDestOnMap.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChooseDestOnMap.sizePolicy().hasHeightForWidth())
        self.pushButtonChooseDestOnMap.setSizePolicy(sizePolicy)
        self.pushButtonChooseDestOnMap.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonChooseDestOnMap.setObjectName(_fromUtf8("pushButtonChooseDestOnMap"))
        self.gridLayout.addWidget(self.pushButtonChooseDestOnMap, 2, 2, 1, 1)
        self.comboBoxOrig = QtGui.QComboBox(self.layoutWidget_3)
        self.comboBoxOrig.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxOrig.sizePolicy().hasHeightForWidth())
        self.comboBoxOrig.setSizePolicy(sizePolicy)
        self.comboBoxOrig.setObjectName(_fromUtf8("comboBoxOrig"))
        self.gridLayout.addWidget(self.comboBoxOrig, 0, 1, 1, 1)
        self.pushButtonInvertOD = QtGui.QPushButton(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonInvertOD.sizePolicy().hasHeightForWidth())
        self.pushButtonInvertOD.setSizePolicy(sizePolicy)
        self.pushButtonInvertOD.setObjectName(_fromUtf8("pushButtonInvertOD"))
        self.gridLayout.addWidget(self.pushButtonInvertOD, 1, 2, 1, 1)
        self.toolBoxPaths.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.layoutWidget1 = QtGui.QWidget(self.page_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 311, 29))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.comboBoxPathsTreeOD = QtGui.QComboBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPathsTreeOD.sizePolicy().hasHeightForWidth())
        self.comboBoxPathsTreeOD.setSizePolicy(sizePolicy)
        self.comboBoxPathsTreeOD.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxPathsTreeOD.setObjectName(_fromUtf8("comboBoxPathsTreeOD"))
        self.comboBoxPathsTreeOD.addItem(_fromUtf8(""))
        self.comboBoxPathsTreeOD.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBoxPathsTreeOD)
        self.comboBoxPathsTreeRootNode = QtGui.QComboBox(self.layoutWidget1)
        self.comboBoxPathsTreeRootNode.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPathsTreeRootNode.sizePolicy().hasHeightForWidth())
        self.comboBoxPathsTreeRootNode.setSizePolicy(sizePolicy)
        self.comboBoxPathsTreeRootNode.setObjectName(_fromUtf8("comboBoxPathsTreeRootNode"))
        self.horizontalLayout_6.addWidget(self.comboBoxPathsTreeRootNode)
        self.pushButtonChoosePathsTreeRootOnMap = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonChoosePathsTreeRootOnMap.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChoosePathsTreeRootOnMap.sizePolicy().hasHeightForWidth())
        self.pushButtonChoosePathsTreeRootOnMap.setSizePolicy(sizePolicy)
        self.pushButtonChoosePathsTreeRootOnMap.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonChoosePathsTreeRootOnMap.setObjectName(_fromUtf8("pushButtonChoosePathsTreeRootOnMap"))
        self.horizontalLayout_6.addWidget(self.pushButtonChoosePathsTreeRootOnMap)
        self.toolBoxPaths.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 321, 170))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.layoutWidget_10 = QtGui.QWidget(self.page_3)
        self.layoutWidget_10.setGeometry(QtCore.QRect(10, 0, 311, 151))
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget_10)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButtonRemovePathsTreesRoots = QtGui.QPushButton(self.layoutWidget_10)
        self.pushButtonRemovePathsTreesRoots.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemovePathsTreesRoots.sizePolicy().hasHeightForWidth())
        self.pushButtonRemovePathsTreesRoots.setSizePolicy(sizePolicy)
        self.pushButtonRemovePathsTreesRoots.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonRemovePathsTreesRoots.setObjectName(_fromUtf8("pushButtonRemovePathsTreesRoots"))
        self.gridLayout_2.addWidget(self.pushButtonRemovePathsTreesRoots, 1, 3, 1, 1)
        self.pushButtonChoosePathsTreesRootsOnMap = QtGui.QPushButton(self.layoutWidget_10)
        self.pushButtonChoosePathsTreesRootsOnMap.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChoosePathsTreesRootsOnMap.sizePolicy().hasHeightForWidth())
        self.pushButtonChoosePathsTreesRootsOnMap.setSizePolicy(sizePolicy)
        self.pushButtonChoosePathsTreesRootsOnMap.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonChoosePathsTreesRootsOnMap.setObjectName(_fromUtf8("pushButtonChoosePathsTreesRootsOnMap"))
        self.gridLayout_2.addWidget(self.pushButtonChoosePathsTreesRootsOnMap, 0, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_9 = QtGui.QLabel(self.layoutWidget_10)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.comboBoxNodeAg = QtGui.QComboBox(self.layoutWidget_10)
        self.comboBoxNodeAg.setObjectName(_fromUtf8("comboBoxNodeAg"))
        self.horizontalLayout.addWidget(self.comboBoxNodeAg)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 4)
        self.listViewNodes = QtGui.QListView(self.layoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewNodes.sizePolicy().hasHeightForWidth())
        self.listViewNodes.setSizePolicy(sizePolicy)
        self.listViewNodes.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listViewNodes.setAlternatingRowColors(True)
        self.listViewNodes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewNodes.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listViewNodes.setObjectName(_fromUtf8("listViewNodes"))
        self.gridLayout_2.addWidget(self.listViewNodes, 0, 2, 3, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 3, 1, 1)
        self.comboBoxCombPathsTreesOD = QtGui.QComboBox(self.layoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCombPathsTreesOD.sizePolicy().hasHeightForWidth())
        self.comboBoxCombPathsTreesOD.setSizePolicy(sizePolicy)
        self.comboBoxCombPathsTreesOD.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxCombPathsTreesOD.setObjectName(_fromUtf8("comboBoxCombPathsTreesOD"))
        self.comboBoxCombPathsTreesOD.addItem(_fromUtf8(""))
        self.comboBoxCombPathsTreesOD.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxCombPathsTreesOD, 0, 0, 3, 2)
        self.toolBoxPaths.addItem(self.page_3, _fromUtf8(""))
        self.layoutWidget2 = QtGui.QWidget(self.groupBoxPaths)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 60, 311, 22))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_29 = QtGui.QLabel(self.layoutWidget2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_13.addWidget(self.label_29)
        self.comboBoxCriterion = QtGui.QComboBox(self.layoutWidget2)
        self.comboBoxCriterion.setObjectName(_fromUtf8("comboBoxCriterion"))
        self.horizontalLayout_13.addWidget(self.comboBoxCriterion)
        self.groupBoxPathsParameters = QtGui.QGroupBox(self.tab_5)
        self.groupBoxPathsParameters.setEnabled(True)
        self.groupBoxPathsParameters.setGeometry(QtCore.QRect(360, 280, 271, 161))
        self.groupBoxPathsParameters.setObjectName(_fromUtf8("groupBoxPathsParameters"))
        self.layoutWidget_8 = QtGui.QWidget(self.groupBoxPathsParameters)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 30, 251, 111))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.gridLayout_13 = QtGui.QGridLayout(self.layoutWidget_8)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.spinBoxMaxCost = QtGui.QSpinBox(self.layoutWidget_8)
        self.spinBoxMaxCost.setMaximum(600)
        self.spinBoxMaxCost.setProperty("value", 60)
        self.spinBoxMaxCost.setObjectName(_fromUtf8("spinBoxMaxCost"))
        self.gridLayout_13.addWidget(self.spinBoxMaxCost, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget_8)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_13.addWidget(self.label_7, 0, 3, 1, 1)
        self.labelTpsStatVP = QtGui.QLabel(self.layoutWidget_8)
        self.labelTpsStatVP.setObjectName(_fromUtf8("labelTpsStatVP"))
        self.gridLayout_13.addWidget(self.labelTpsStatVP, 1, 0, 1, 2)
        self.label_14 = QtGui.QLabel(self.layoutWidget_8)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_13.addWidget(self.label_14, 2, 3, 1, 1)
        self.doubleSpinBoxCyclingSpeed = QtGui.QDoubleSpinBox(self.layoutWidget_8)
        self.doubleSpinBoxCyclingSpeed.setProperty("value", 11.0)
        self.doubleSpinBoxCyclingSpeed.setObjectName(_fromUtf8("doubleSpinBoxCyclingSpeed"))
        self.gridLayout_13.addWidget(self.doubleSpinBoxCyclingSpeed, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget_8)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_13.addWidget(self.label_5, 0, 0, 1, 2)
        self.label_13 = QtGui.QLabel(self.layoutWidget_8)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_13.addWidget(self.label_13, 1, 3, 1, 1)
        self.doubleSpinBoxWalkingSpeed = QtGui.QDoubleSpinBox(self.layoutWidget_8)
        self.doubleSpinBoxWalkingSpeed.setProperty("value", 3.6)
        self.doubleSpinBoxWalkingSpeed.setObjectName(_fromUtf8("doubleSpinBoxWalkingSpeed"))
        self.gridLayout_13.addWidget(self.doubleSpinBoxWalkingSpeed, 1, 2, 1, 1)
        self.labelTpsStatVelo = QtGui.QLabel(self.layoutWidget_8)
        self.labelTpsStatVelo.setObjectName(_fromUtf8("labelTpsStatVelo"))
        self.gridLayout_13.addWidget(self.labelTpsStatVelo, 2, 0, 1, 2)
        self.Tabs.addTab(self.tab_5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBoxPTNetworks = QtGui.QGroupBox(self.tab_2)
        self.groupBoxPTNetworks.setGeometry(QtCore.QRect(10, 10, 341, 121))
        self.groupBoxPTNetworks.setObjectName(_fromUtf8("groupBoxPTNetworks"))
        self.listViewPTNetworks = QtGui.QListView(self.groupBoxPTNetworks)
        self.listViewPTNetworks.setGeometry(QtCore.QRect(10, 40, 321, 71))
        self.listViewPTNetworks.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listViewPTNetworks.setAlternatingRowColors(True)
        self.listViewPTNetworks.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.listViewPTNetworks.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listViewPTNetworks.setObjectName(_fromUtf8("listViewPTNetworks"))
        self.groupBoxAgencies = QtGui.QGroupBox(self.tab_2)
        self.groupBoxAgencies.setGeometry(QtCore.QRect(10, 140, 341, 211))
        self.groupBoxAgencies.setObjectName(_fromUtf8("groupBoxAgencies"))
        self.tableViewAgencies = QtGui.QTableView(self.groupBoxAgencies)
        self.tableViewAgencies.setGeometry(QtCore.QRect(10, 40, 321, 161))
        self.tableViewAgencies.setAlternatingRowColors(True)
        self.tableViewAgencies.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableViewAgencies.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableViewAgencies.setObjectName(_fromUtf8("tableViewAgencies"))
        self.groupBoxTransportModes = QtGui.QGroupBox(self.tab_2)
        self.groupBoxTransportModes.setEnabled(True)
        self.groupBoxTransportModes.setGeometry(QtCore.QRect(370, 10, 261, 341))
        self.groupBoxTransportModes.setObjectName(_fromUtf8("groupBoxTransportModes"))
        self.layoutWidget_14 = QtGui.QWidget(self.groupBoxTransportModes)
        self.layoutWidget_14.setGeometry(QtCore.QRect(10, 40, 241, 131))
        self.layoutWidget_14.setObjectName(_fromUtf8("layoutWidget_14"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.layoutWidget_14)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.listViewIModes = QtGui.QListView(self.layoutWidget_14)
        self.listViewIModes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewIModes.setObjectName(_fromUtf8("listViewIModes"))
        self.horizontalLayout_3.addWidget(self.listViewIModes)
        self.layoutWidget_16 = QtGui.QWidget(self.groupBoxTransportModes)
        self.layoutWidget_16.setGeometry(QtCore.QRect(10, 180, 241, 141))
        self.layoutWidget_16.setObjectName(_fromUtf8("layoutWidget_16"))
        self.gridLayout_14 = QtGui.QGridLayout(self.layoutWidget_16)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_22 = QtGui.QLabel(self.layoutWidget_16)
        self.label_22.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_14.addWidget(self.label_22, 0, 0, 1, 1)
        self.listViewPTModes = QtGui.QListView(self.layoutWidget_16)
        self.listViewPTModes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewPTModes.setObjectName(_fromUtf8("listViewPTModes"))
        self.gridLayout_14.addWidget(self.listViewPTModes, 0, 1, 2, 1)
        self.label_23 = QtGui.QLabel(self.layoutWidget_16)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_14.addWidget(self.label_23, 1, 0, 1, 1)
        self.Tabs.addTab(self.tab_2, _fromUtf8(""))
        self.TabIndicateurs = QtGui.QWidget()
        self.TabIndicateurs.setObjectName(_fromUtf8("TabIndicateurs"))
        self.groupBoxDays = QtGui.QGroupBox(self.TabIndicateurs)
        self.groupBoxDays.setGeometry(QtCore.QRect(10, 10, 321, 361))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBoxDays.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxDays.setFont(font)
        self.groupBoxDays.setObjectName(_fromUtf8("groupBoxDays"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBoxDays)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 30, 291, 19))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButtonPreciseDate = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButtonPreciseDate.setChecked(True)
        self.radioButtonPreciseDate.setObjectName(_fromUtf8("radioButtonPreciseDate"))
        self.horizontalLayout_4.addWidget(self.radioButtonPreciseDate)
        self.radioButtonDayType = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButtonDayType.setObjectName(_fromUtf8("radioButtonDayType"))
        self.horizontalLayout_4.addWidget(self.radioButtonDayType)
        self.toolBoxDays = QtGui.QToolBox(self.groupBoxDays)
        self.toolBoxDays.setGeometry(QtCore.QRect(20, 60, 291, 281))
        self.toolBoxDays.setObjectName(_fromUtf8("toolBoxDays"))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.calendarWidget = QtGui.QCalendarWidget(self.page_4)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 291, 221))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.toolBoxDays.addItem(self.page_4, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.layoutWidget_12 = QtGui.QWidget(self.page_5)
        self.layoutWidget_12.setGeometry(QtCore.QRect(0, 0, 291, 161))
        self.layoutWidget_12.setObjectName(_fromUtf8("layoutWidget_12"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget_12)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelLastDay = QtGui.QLabel(self.layoutWidget_12)
        self.labelLastDay.setEnabled(True)
        self.labelLastDay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelLastDay.setObjectName(_fromUtf8("labelLastDay"))
        self.gridLayout_3.addWidget(self.labelLastDay, 3, 0, 1, 1)
        self.comboBoxDayType = QtGui.QComboBox(self.layoutWidget_12)
        self.comboBoxDayType.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDayType.sizePolicy().hasHeightForWidth())
        self.comboBoxDayType.setSizePolicy(sizePolicy)
        self.comboBoxDayType.setObjectName(_fromUtf8("comboBoxDayType"))
        self.gridLayout_3.addWidget(self.comboBoxDayType, 0, 0, 1, 2)
        self.dateEditPerStart = QtGui.QDateEdit(self.layoutWidget_12)
        self.dateEditPerStart.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEditPerStart.sizePolicy().hasHeightForWidth())
        self.dateEditPerStart.setSizePolicy(sizePolicy)
        self.dateEditPerStart.setObjectName(_fromUtf8("dateEditPerStart"))
        self.gridLayout_3.addWidget(self.dateEditPerStart, 2, 1, 1, 1)
        self.comboBoxPerType = QtGui.QComboBox(self.layoutWidget_12)
        self.comboBoxPerType.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPerType.sizePolicy().hasHeightForWidth())
        self.comboBoxPerType.setSizePolicy(sizePolicy)
        self.comboBoxPerType.setObjectName(_fromUtf8("comboBoxPerType"))
        self.gridLayout_3.addWidget(self.comboBoxPerType, 1, 0, 1, 2)
        self.dateEditPerEnd = QtGui.QDateEdit(self.layoutWidget_12)
        self.dateEditPerEnd.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEditPerEnd.sizePolicy().hasHeightForWidth())
        self.dateEditPerEnd.setSizePolicy(sizePolicy)
        self.dateEditPerEnd.setObjectName(_fromUtf8("dateEditPerEnd"))
        self.gridLayout_3.addWidget(self.dateEditPerEnd, 3, 1, 1, 1)
        self.labelFirstDay = QtGui.QLabel(self.layoutWidget_12)
        self.labelFirstDay.setEnabled(True)
        self.labelFirstDay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFirstDay.setObjectName(_fromUtf8("labelFirstDay"))
        self.gridLayout_3.addWidget(self.labelFirstDay, 2, 0, 1, 1)
        self.comboBoxDayAg = QtGui.QComboBox(self.layoutWidget_12)
        self.comboBoxDayAg.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDayAg.sizePolicy().hasHeightForWidth())
        self.comboBoxDayAg.setSizePolicy(sizePolicy)
        self.comboBoxDayAg.setObjectName(_fromUtf8("comboBoxDayAg"))
        self.gridLayout_3.addWidget(self.comboBoxDayAg, 4, 1, 2, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget_12)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 2, 1)
        self.toolBoxDays.addItem(self.page_5, _fromUtf8(""))
        self.groupBoxTimePeriod = QtGui.QGroupBox(self.TabIndicateurs)
        self.groupBoxTimePeriod.setGeometry(QtCore.QRect(350, 10, 291, 361))
        self.groupBoxTimePeriod.setObjectName(_fromUtf8("groupBoxTimePeriod"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBoxTimePeriod)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 30, 271, 20))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.radioButtonTimePoint = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButtonTimePoint.setEnabled(True)
        self.radioButtonTimePoint.setObjectName(_fromUtf8("radioButtonTimePoint"))
        self.horizontalLayout_10.addWidget(self.radioButtonTimePoint)
        self.radioButtonTimePeriod = QtGui.QRadioButton(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonTimePeriod.sizePolicy().hasHeightForWidth())
        self.radioButtonTimePeriod.setSizePolicy(sizePolicy)
        self.radioButtonTimePeriod.setChecked(False)
        self.radioButtonTimePeriod.setObjectName(_fromUtf8("radioButtonTimePeriod"))
        self.horizontalLayout_10.addWidget(self.radioButtonTimePeriod)
        self.toolBoxTime = QtGui.QToolBox(self.groupBoxTimePeriod)
        self.toolBoxTime.setEnabled(True)
        self.toolBoxTime.setGeometry(QtCore.QRect(10, 110, 271, 201))
        self.toolBoxTime.setObjectName(_fromUtf8("toolBoxTime"))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.layoutWidget4 = QtGui.QWidget(self.page_6)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 10, 271, 22))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.labelTimeConstraint = QtGui.QLabel(self.layoutWidget4)
        self.labelTimeConstraint.setObjectName(_fromUtf8("labelTimeConstraint"))
        self.horizontalLayout_14.addWidget(self.labelTimeConstraint)
        self.timeEditTimePoint = QtGui.QTimeEdit(self.layoutWidget4)
        self.timeEditTimePoint.setEnabled(True)
        self.timeEditTimePoint.setTime(QtCore.QTime(17, 0, 0))
        self.timeEditTimePoint.setCalendarPopup(True)
        self.timeEditTimePoint.setObjectName(_fromUtf8("timeEditTimePoint"))
        self.horizontalLayout_14.addWidget(self.timeEditTimePoint)
        self.toolBoxTime.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.layoutWidget5 = QtGui.QWidget(self.page_7)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 10, 271, 31))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.timeEditTimeEnd = QtGui.QTimeEdit(self.layoutWidget5)
        self.timeEditTimeEnd.setEnabled(True)
        self.timeEditTimeEnd.setTime(QtCore.QTime(23, 59, 0))
        self.timeEditTimeEnd.setCalendarPopup(True)
        self.timeEditTimeEnd.setObjectName(_fromUtf8("timeEditTimeEnd"))
        self.gridLayout_6.addWidget(self.timeEditTimeEnd, 0, 3, 1, 1)
        self.labelToTime = QtGui.QLabel(self.layoutWidget5)
        self.labelToTime.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelToTime.sizePolicy().hasHeightForWidth())
        self.labelToTime.setSizePolicy(sizePolicy)
        self.labelToTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelToTime.setObjectName(_fromUtf8("labelToTime"))
        self.gridLayout_6.addWidget(self.labelToTime, 0, 2, 1, 1)
        self.labelFromTime = QtGui.QLabel(self.layoutWidget5)
        self.labelFromTime.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFromTime.sizePolicy().hasHeightForWidth())
        self.labelFromTime.setSizePolicy(sizePolicy)
        self.labelFromTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFromTime.setObjectName(_fromUtf8("labelFromTime"))
        self.gridLayout_6.addWidget(self.labelFromTime, 0, 0, 1, 1)
        self.timeEditTimeStart = QtGui.QTimeEdit(self.layoutWidget5)
        self.timeEditTimeStart.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEditTimeStart.sizePolicy().hasHeightForWidth())
        self.timeEditTimeStart.setSizePolicy(sizePolicy)
        self.timeEditTimeStart.setTime(QtCore.QTime(0, 0, 0))
        self.timeEditTimeStart.setObjectName(_fromUtf8("timeEditTimeStart"))
        self.gridLayout_6.addWidget(self.timeEditTimeStart, 0, 1, 1, 1)
        self.layoutWidget6 = QtGui.QWidget(self.page_7)
        self.layoutWidget6.setGeometry(QtCore.QRect(0, 110, 271, 29))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_24 = QtGui.QLabel(self.layoutWidget6)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_5.addWidget(self.label_24)
        self.comboBoxTimeAg = QtGui.QComboBox(self.layoutWidget6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxTimeAg.sizePolicy().hasHeightForWidth())
        self.comboBoxTimeAg.setSizePolicy(sizePolicy)
        self.comboBoxTimeAg.setObjectName(_fromUtf8("comboBoxTimeAg"))
        self.horizontalLayout_5.addWidget(self.comboBoxTimeAg)
        self.layoutWidget7 = QtGui.QWidget(self.page_7)
        self.layoutWidget7.setGeometry(QtCore.QRect(0, 50, 271, 57))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.layoutWidget7)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.radioButtonTimeInterval = QtGui.QRadioButton(self.layoutWidget7)
        self.radioButtonTimeInterval.setChecked(True)
        self.radioButtonTimeInterval.setObjectName(_fromUtf8("radioButtonTimeInterval"))
        self.gridLayout_10.addWidget(self.radioButtonTimeInterval, 0, 0, 1, 1)
        self.radioButtonAllServices = QtGui.QRadioButton(self.layoutWidget7)
        self.radioButtonAllServices.setObjectName(_fromUtf8("radioButtonAllServices"))
        self.gridLayout_10.addWidget(self.radioButtonAllServices, 1, 0, 1, 2)
        self.timeEditTimeInterval = QtGui.QTimeEdit(self.layoutWidget7)
        self.timeEditTimeInterval.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEditTimeInterval.sizePolicy().hasHeightForWidth())
        self.timeEditTimeInterval.setSizePolicy(sizePolicy)
        self.timeEditTimeInterval.setTime(QtCore.QTime(0, 30, 0))
        self.timeEditTimeInterval.setObjectName(_fromUtf8("timeEditTimeInterval"))
        self.gridLayout_10.addWidget(self.timeEditTimeInterval, 0, 1, 1, 1)
        self.toolBoxTime.addItem(self.page_7, _fromUtf8(""))
        self.layoutWidget8 = QtGui.QWidget(self.groupBoxTimePeriod)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 70, 271, 22))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_11 = QtGui.QLabel(self.layoutWidget8)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_8.addWidget(self.label_11)
        self.comboBoxTimeConstraint = QtGui.QComboBox(self.layoutWidget8)
        self.comboBoxTimeConstraint.setObjectName(_fromUtf8("comboBoxTimeConstraint"))
        self.comboBoxTimeConstraint.addItem(_fromUtf8(""))
        self.comboBoxTimeConstraint.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.comboBoxTimeConstraint)
        self.Tabs.addTab(self.TabIndicateurs, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBoxPerimetre = QtGui.QGroupBox(self.tab)
        self.groupBoxPerimetre.setEnabled(True)
        self.groupBoxPerimetre.setGeometry(QtCore.QRect(10, 10, 621, 71))
        self.groupBoxPerimetre.setObjectName(_fromUtf8("groupBoxPerimetre"))
        self.layoutWidget_4 = QtGui.QWidget(self.groupBoxPerimetre)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 30, 601, 31))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.comboBoxZone = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBoxZone.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxZone.sizePolicy().hasHeightForWidth())
        self.comboBoxZone.setSizePolicy(sizePolicy)
        self.comboBoxZone.setObjectName(_fromUtf8("comboBoxZone"))
        self.gridLayout_4.addWidget(self.comboBoxZone, 0, 4, 1, 1)
        self.labelPerimeterType = QtGui.QLabel(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPerimeterType.sizePolicy().hasHeightForWidth())
        self.labelPerimeterType.setSizePolicy(sizePolicy)
        self.labelPerimeterType.setObjectName(_fromUtf8("labelPerimeterType"))
        self.gridLayout_4.addWidget(self.labelPerimeterType, 0, 0, 1, 1)
        self.labelPerimeter = QtGui.QLabel(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPerimeter.sizePolicy().hasHeightForWidth())
        self.labelPerimeter.setSizePolicy(sizePolicy)
        self.labelPerimeter.setObjectName(_fromUtf8("labelPerimeter"))
        self.gridLayout_4.addWidget(self.labelPerimeter, 0, 3, 1, 1)
        self.comboBoxZoningFilter = QtGui.QComboBox(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxZoningFilter.sizePolicy().hasHeightForWidth())
        self.comboBoxZoningFilter.setSizePolicy(sizePolicy)
        self.comboBoxZoningFilter.setObjectName(_fromUtf8("comboBoxZoningFilter"))
        self.gridLayout_4.addWidget(self.comboBoxZoningFilter, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.groupBoxForcRoute = QtGui.QGroupBox(self.tab)
        self.groupBoxForcRoute.setGeometry(QtCore.QRect(10, 100, 341, 71))
        self.groupBoxForcRoute.setObjectName(_fromUtf8("groupBoxForcRoute"))
        self.comboBoxForcRoute = QtGui.QComboBox(self.groupBoxForcRoute)
        self.comboBoxForcRoute.setGeometry(QtCore.QRect(10, 30, 321, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxForcRoute.sizePolicy().hasHeightForWidth())
        self.comboBoxForcRoute.setSizePolicy(sizePolicy)
        self.comboBoxForcRoute.setObjectName(_fromUtf8("comboBoxForcRoute"))
        self.groupBoxForcStop = QtGui.QGroupBox(self.tab)
        self.groupBoxForcStop.setGeometry(QtCore.QRect(360, 100, 261, 71))
        self.groupBoxForcStop.setObjectName(_fromUtf8("groupBoxForcStop"))
        self.layoutWidget_6 = QtGui.QWidget(self.groupBoxForcStop)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 30, 241, 25))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.comboBoxForcStop = QtGui.QComboBox(self.layoutWidget_6)
        self.comboBoxForcStop.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxForcStop.sizePolicy().hasHeightForWidth())
        self.comboBoxForcStop.setSizePolicy(sizePolicy)
        self.comboBoxForcStop.setObjectName(_fromUtf8("comboBoxForcStop"))
        self.horizontalLayout_7.addWidget(self.comboBoxForcStop)
        self.pushButtonChooseForcStopOnMap = QtGui.QPushButton(self.layoutWidget_6)
        self.pushButtonChooseForcStopOnMap.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChooseForcStopOnMap.sizePolicy().hasHeightForWidth())
        self.pushButtonChooseForcStopOnMap.setSizePolicy(sizePolicy)
        self.pushButtonChooseForcStopOnMap.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonChooseForcStopOnMap.setObjectName(_fromUtf8("pushButtonChooseForcStopOnMap"))
        self.horizontalLayout_7.addWidget(self.pushButtonChooseForcStopOnMap)
        self.Tabs.addTab(self.tab, _fromUtf8(""))
        self.layoutWidget9 = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget9.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_23.setMargin(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.layoutWidget10 = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget10.setGeometry(QtCore.QRect(10, 480, 641, 31))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget10)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.labelElapsedTime = QtGui.QLabel(self.layoutWidget10)
        self.labelElapsedTime.setText(_fromUtf8(""))
        self.labelElapsedTime.setObjectName(_fromUtf8("labelElapsedTime"))
        self.gridLayout_5.addWidget(self.labelElapsedTime, 0, 1, 1, 1)
        self.pushButtonIndicCalculate = QtGui.QPushButton(self.layoutWidget10)
        self.pushButtonIndicCalculate.setObjectName(_fromUtf8("pushButtonIndicCalculate"))
        self.gridLayout_5.addWidget(self.pushButtonIndicCalculate, 0, 3, 1, 1)
        self.pushButtonReinitCalc = QtGui.QPushButton(self.layoutWidget10)
        self.pushButtonReinitCalc.setObjectName(_fromUtf8("pushButtonReinitCalc"))
        self.gridLayout_5.addWidget(self.pushButtonReinitCalc, 0, 0, 1, 1)
        self.pushButtonIndicReqGenerate = QtGui.QPushButton(self.layoutWidget10)
        self.pushButtonIndicReqGenerate.setObjectName(_fromUtf8("pushButtonIndicReqGenerate"))
        self.gridLayout_5.addWidget(self.pushButtonIndicReqGenerate, 0, 2, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.Tabs.setCurrentIndex(0)
        self.toolBoxPaths.setCurrentIndex(2)
        self.toolBoxDays.setCurrentIndex(0)
        self.toolBoxTime.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "TempusAccess - Paramétrage des calculs", None))
        self.groupBoxObjType.setTitle(_translate("DockWidget", "Objets de base", None))
        self.comboBoxObjType.setToolTip(_translate("DockWidget", "<html><head/><body><p>Type d\'objet unitaire pour le calcul de la requête</p></body></html>", None))
        self.groupBoxIndicators.setTitle(_translate("DockWidget", "Indicateurs", None))
        self.labelPerimeterType_2.setText(_translate("DockWidget", "Zonage", None))
        self.groupBoxPaths.setTitle(_translate("DockWidget", "Paramétrage des itinéraires et arborescences", None))
        self.label_33.setText(_translate("DockWidget", "Type de noeuds O et D", None))
        self.labelFromNode.setText(_translate("DockWidget", "O", None))
        self.pushButtonChooseOrigOnMap.setText(_translate("DockWidget", "+", None))
        self.labelToNode.setText(_translate("DockWidget", "D", None))
        self.pushButtonChooseDestOnMap.setText(_translate("DockWidget", "+", None))
        self.pushButtonInvertOD.setText(_translate("DockWidget", "O <-> D", None))
        self.toolBoxPaths.setItemText(self.toolBoxPaths.indexOf(self.page), _translate("DockWidget", "Itinéraires O-D", None))
        self.comboBoxPathsTreeOD.setItemText(0, _translate("DockWidget", "Origine", None))
        self.comboBoxPathsTreeOD.setItemText(1, _translate("DockWidget", "Destination", None))
        self.pushButtonChoosePathsTreeRootOnMap.setText(_translate("DockWidget", "+", None))
        self.toolBoxPaths.setItemText(self.toolBoxPaths.indexOf(self.page_2), _translate("DockWidget", "Arborescence O-* ou *-D", None))
        self.pushButtonRemovePathsTreesRoots.setText(_translate("DockWidget", "-", None))
        self.pushButtonChoosePathsTreesRootsOnMap.setText(_translate("DockWidget", "+", None))
        self.label_9.setText(_translate("DockWidget", "Méthode d\'agrégation", None))
        self.comboBoxCombPathsTreesOD.setItemText(0, _translate("DockWidget", "Origine(s)", None))
        self.comboBoxCombPathsTreesOD.setItemText(1, _translate("DockWidget", "Destination(s)", None))
        self.toolBoxPaths.setItemText(self.toolBoxPaths.indexOf(self.page_3), _translate("DockWidget", "Combinaison d\'arborescences", None))
        self.label_29.setText(_translate("DockWidget", "Critère d\'optimisation", None))
        self.groupBoxPathsParameters.setTitle(_translate("DockWidget", "Paramétrage des arborescences", None))
        self.label_7.setText(_translate("DockWidget", "minutes", None))
        self.labelTpsStatVP.setText(_translate("DockWidget", "Vitesse marche", None))
        self.label_14.setText(_translate("DockWidget", "km/h", None))
        self.label_5.setText(_translate("DockWidget", "Valeur maximum", None))
        self.label_13.setText(_translate("DockWidget", "km/h", None))
        self.labelTpsStatVelo.setText(_translate("DockWidget", "Vitesse vélo", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_5), _translate("DockWidget", "Objets", None))
        self.groupBoxPTNetworks.setTitle(_translate("DockWidget", "Réseau de transport collectif", None))
        self.groupBoxAgencies.setTitle(_translate("DockWidget", "Transporteurs", None))
        self.groupBoxTransportModes.setTitle(_translate("DockWidget", "Modes de transport", None))
        self.label_2.setText(_translate("DockWidget", "Individuels", None))
        self.label_22.setText(_translate("DockWidget", "Transport", None))
        self.label_23.setText(_translate("DockWidget", "collectif", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("DockWidget", "Réseaux et modes", None))
        self.groupBoxDays.setTitle(_translate("DockWidget", "Jours", None))
        self.radioButtonPreciseDate.setText(_translate("DockWidget", "Date précise", None))
        self.radioButtonDayType.setText(_translate("DockWidget", "Type de jour", None))
        self.toolBoxDays.setItemText(self.toolBoxDays.indexOf(self.page_4), _translate("DockWidget", "Date précise", None))
        self.labelLastDay.setText(_translate("DockWidget", "Fin période", None))
        self.labelFirstDay.setText(_translate("DockWidget", "Début période", None))
        self.label_8.setText(_translate("DockWidget", "Méthode d\'agrégation", None))
        self.toolBoxDays.setItemText(self.toolBoxDays.indexOf(self.page_5), _translate("DockWidget", "Type de jour", None))
        self.groupBoxTimePeriod.setTitle(_translate("DockWidget", "Heure - Période horaire", None))
        self.radioButtonTimePoint.setText(_translate("DockWidget", "A une heure précise", None))
        self.radioButtonTimePeriod.setText(_translate("DockWidget", "Sur une période horaire", None))
        self.labelTimeConstraint.setText(_translate("DockWidget", "Partir après...", None))
        self.toolBoxTime.setItemText(self.toolBoxTime.indexOf(self.page_6), _translate("DockWidget", "Heure précise", None))
        self.labelToTime.setText(_translate("DockWidget", "et", None))
        self.labelFromTime.setText(_translate("DockWidget", "Départ entre", None))
        self.label_24.setText(_translate("DockWidget", "Méthode d\'agrégation", None))
        self.radioButtonTimeInterval.setText(_translate("DockWidget", "Toutes les", None))
        self.radioButtonAllServices.setText(_translate("DockWidget", "Chercher tous les services de la période", None))
        self.toolBoxTime.setItemText(self.toolBoxTime.indexOf(self.page_7), _translate("DockWidget", "Période horaire", None))
        self.label_11.setText(_translate("DockWidget", "Type de contrainte horaire", None))
        self.comboBoxTimeConstraint.setItemText(0, _translate("DockWidget", "Sur l\'heure de départ", None))
        self.comboBoxTimeConstraint.setItemText(1, _translate("DockWidget", "Sur l\'heure d\'arrivée", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.TabIndicateurs), _translate("DockWidget", "Jours et heures", None))
        self.groupBoxPerimetre.setTitle(_translate("DockWidget", "Restreindre à une zone", None))
        self.labelPerimeterType.setText(_translate("DockWidget", "Zonage", None))
        self.labelPerimeter.setText(_translate("DockWidget", "Zone", None))
        self.groupBoxForcRoute.setTitle(_translate("DockWidget", "Obliger la desserte par une ligne", None))
        self.groupBoxForcStop.setTitle(_translate("DockWidget", "Obliger le passage par un arrêt", None))
        self.pushButtonChooseForcStopOnMap.setText(_translate("DockWidget", "+", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("DockWidget", "Filtres", None))
        self.pushButtonIndicCalculate.setText(_translate("DockWidget", "Lancer la requête", None))
        self.pushButtonReinitCalc.setText(_translate("DockWidget", "Nouveau calcul", None))
        self.pushButtonIndicReqGenerate.setText(_translate("DockWidget", "Générer la requête...", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DockWidget = QtGui.QDockWidget()
    ui = Ui_DockWidget()
    ui.setupUi(DockWidget)
    DockWidget.show()
    sys.exit(app.exec_())

