pyuic4 -x -d -o "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_DBConnectionDialog.py" "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_DBConnectionDialog.ui"
pyuic4 -x -d -o "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_manageRoadNetworkDialog.py" "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_manageRoadNetworkDialog.ui"
pyuic4 -x -d -o "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_managePTNetworkDialog.py" "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_managePTNetworkDialog.ui"
pyuic4 -x -d -o "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_managePOIDialog.py" "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_managePOIDialog.ui"
pyuic4 -x -d -o "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_TempusAccessDockWidget.py" "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_TempusAccessDockWidget.ui"
pyuic4 -x -d -o "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_importPTNetworkDialog.py" "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_importPTNetworkDialog.ui"
pyuic4 -x -d -o "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_importRoadNetworkDialog.py" "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_importRoadNetworkDialog.ui"
pyuic4 -x -d -o "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_importPOIDialog.py" "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_importPOIDialog.ui"
pyuic4 -x -d -o "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_importAreasDialog.py" "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_importAreasDialog.ui"
pyrcc4 -o "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\resources.py" "C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\resources.qrc"

