# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_DBConnectionDialog.ui'
#
# Created: Fri Aug 31 17:00:28 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(698, 339)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 270, 641, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonUseDB = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonUseDB.setObjectName(_fromUtf8("pushButtonUseDB"))
        self.gridLayout.addWidget(self.pushButtonUseDB, 0, 2, 1, 1)
        self.pushButtonImportDB = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonImportDB.setEnabled(True)
        self.pushButtonImportDB.setObjectName(_fromUtf8("pushButtonImportDB"))
        self.gridLayout.addWidget(self.pushButtonImportDB, 0, 0, 1, 1)
        self.pushButtonBackupDB = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonBackupDB.setEnabled(True)
        self.pushButtonBackupDB.setObjectName(_fromUtf8("pushButtonBackupDB"))
        self.gridLayout.addWidget(self.pushButtonBackupDB, 1, 0, 1, 1)
        self.pushButtonCancel = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.gridLayout.addWidget(self.pushButtonCancel, 1, 2, 1, 1)
        self.pushButtonInitDB = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonInitDB.setObjectName(_fromUtf8("pushButtonInitDB"))
        self.gridLayout.addWidget(self.pushButtonInitDB, 1, 1, 1, 1)
        self.pushButtonDelete = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonDelete.setObjectName(_fromUtf8("pushButtonDelete"))
        self.gridLayout.addWidget(self.pushButtonDelete, 0, 1, 1, 1)
        self.groupBoxParam = QtGui.QGroupBox(Dialog)
        self.groupBoxParam.setGeometry(QtCore.QRect(10, 10, 371, 241))
        self.groupBoxParam.setObjectName(_fromUtf8("groupBoxParam"))
        self.layoutWidget_155 = QtGui.QWidget(self.groupBoxParam)
        self.layoutWidget_155.setGeometry(QtCore.QRect(20, 30, 331, 191))
        self.layoutWidget_155.setObjectName(_fromUtf8("layoutWidget_155"))
        self.gridLayout_16 = QtGui.QGridLayout(self.layoutWidget_155)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_194 = QtGui.QLabel(self.layoutWidget_155)
        self.label_194.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_194.setObjectName(_fromUtf8("label_194"))
        self.gridLayout_16.addWidget(self.label_194, 3, 0, 1, 1)
        self.lineEdit_port = QtGui.QLineEdit(self.layoutWidget_155)
        self.lineEdit_port.setObjectName(_fromUtf8("lineEdit_port"))
        self.gridLayout_16.addWidget(self.lineEdit_port, 1, 1, 1, 2)
        self.lineEdit_pwd = QtGui.QLineEdit(self.layoutWidget_155)
        self.lineEdit_pwd.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.lineEdit_pwd.setText(_fromUtf8(""))
        self.lineEdit_pwd.setObjectName(_fromUtf8("lineEdit_pwd"))
        self.gridLayout_16.addWidget(self.lineEdit_pwd, 3, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.layoutWidget_155)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_16.addWidget(self.label_4, 4, 1, 1, 1)
        self.comboBoxDB = QtGui.QComboBox(self.layoutWidget_155)
        self.comboBoxDB.setEditable(True)
        self.comboBoxDB.setObjectName(_fromUtf8("comboBoxDB"))
        self.gridLayout_16.addWidget(self.comboBoxDB, 4, 2, 1, 1)
        self.label_193 = QtGui.QLabel(self.layoutWidget_155)
        self.label_193.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_193.setObjectName(_fromUtf8("label_193"))
        self.gridLayout_16.addWidget(self.label_193, 2, 0, 1, 1)
        self.label_195 = QtGui.QLabel(self.layoutWidget_155)
        self.label_195.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_195.setObjectName(_fromUtf8("label_195"))
        self.gridLayout_16.addWidget(self.label_195, 4, 0, 1, 1)
        self.lineEdit_login = QtGui.QLineEdit(self.layoutWidget_155)
        self.lineEdit_login.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.lineEdit_login.setText(_fromUtf8(""))
        self.lineEdit_login.setObjectName(_fromUtf8("lineEdit_login"))
        self.gridLayout_16.addWidget(self.lineEdit_login, 2, 1, 1, 2)
        self.label_192 = QtGui.QLabel(self.layoutWidget_155)
        self.label_192.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_192.setObjectName(_fromUtf8("label_192"))
        self.gridLayout_16.addWidget(self.label_192, 0, 0, 1, 1)
        self.lineEdit_host = QtGui.QLineEdit(self.layoutWidget_155)
        self.lineEdit_host.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.lineEdit_host.setObjectName(_fromUtf8("lineEdit_host"))
        self.gridLayout_16.addWidget(self.lineEdit_host, 0, 1, 1, 2)
        self.label = QtGui.QLabel(self.layoutWidget_155)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_16.addWidget(self.label, 1, 0, 1, 1)
        self.groupBoxStats = QtGui.QGroupBox(Dialog)
        self.groupBoxStats.setGeometry(QtCore.QRect(390, 10, 301, 181))
        self.groupBoxStats.setObjectName(_fromUtf8("groupBoxStats"))
        self.layoutWidget_156 = QtGui.QWidget(self.groupBoxStats)
        self.layoutWidget_156.setGeometry(QtCore.QRect(20, 30, 261, 141))
        self.layoutWidget_156.setObjectName(_fromUtf8("layoutWidget_156"))
        self.gridLayout_17 = QtGui.QGridLayout(self.layoutWidget_156)
        self.gridLayout_17.setMargin(0)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.labelRouteDataSize = QtGui.QLabel(self.layoutWidget_156)
        self.labelRouteDataSize.setObjectName(_fromUtf8("labelRouteDataSize"))
        self.gridLayout_17.addWidget(self.labelRouteDataSize, 1, 1, 1, 1)
        self.label_197 = QtGui.QLabel(self.layoutWidget_156)
        self.label_197.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_197.setObjectName(_fromUtf8("label_197"))
        self.gridLayout_17.addWidget(self.label_197, 0, 0, 1, 1)
        self.labelPTDataSize = QtGui.QLabel(self.layoutWidget_156)
        self.labelPTDataSize.setObjectName(_fromUtf8("labelPTDataSize"))
        self.gridLayout_17.addWidget(self.labelPTDataSize, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget_156)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_17.addWidget(self.label_2, 3, 0, 1, 1)
        self.labelIndicDataSize = QtGui.QLabel(self.layoutWidget_156)
        self.labelIndicDataSize.setObjectName(_fromUtf8("labelIndicDataSize"))
        self.gridLayout_17.addWidget(self.labelIndicDataSize, 2, 1, 1, 1)
        self.labelAuxDataSize = QtGui.QLabel(self.layoutWidget_156)
        self.labelAuxDataSize.setObjectName(_fromUtf8("labelAuxDataSize"))
        self.gridLayout_17.addWidget(self.labelAuxDataSize, 3, 1, 1, 1)
        self.label_196 = QtGui.QLabel(self.layoutWidget_156)
        self.label_196.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_196.setObjectName(_fromUtf8("label_196"))
        self.gridLayout_17.addWidget(self.label_196, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget_156)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_17.addWidget(self.label_3, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButtonCancel, self.lineEdit_host)
        Dialog.setTabOrder(self.lineEdit_host, self.lineEdit_port)
        Dialog.setTabOrder(self.lineEdit_port, self.lineEdit_login)
        Dialog.setTabOrder(self.lineEdit_login, self.lineEdit_pwd)
        Dialog.setTabOrder(self.lineEdit_pwd, self.comboBoxDB)
        Dialog.setTabOrder(self.comboBoxDB, self.pushButtonBackupDB)
        Dialog.setTabOrder(self.pushButtonBackupDB, self.pushButtonImportDB)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Gestion des bases de données", None))
        self.pushButtonUseDB.setToolTip(_translate("Dialog", "<html><head/><body><p>Charge les données de la base dans la fenêtre cartographique de QGIS et dans l\'interface du plugin. </p></body></html>", None))
        self.pushButtonUseDB.setText(_translate("Dialog", "Charger dans QGIS", None))
        self.pushButtonImportDB.setToolTip(_translate("Dialog", "<html><head/><body><p>Ecrase toutes les données déjà présentes dans la base et les remplace par les données du fichier de sauvegarde choisi.  </p></body></html>", None))
        self.pushButtonImportDB.setText(_translate("Dialog", "Importer une sauvegarde...", None))
        self.pushButtonBackupDB.setToolTip(_translate("Dialog", "<html><head/><body><p>Sauvegarde la base dans un fichier externe pour pouvoir la recharger ultérieurement. </p></body></html>", None))
        self.pushButtonBackupDB.setText(_translate("Dialog", "Sauvegarder la base...", None))
        self.pushButtonCancel.setText(_translate("Dialog", "Annuler", None))
        self.pushButtonInitDB.setToolTip(_translate("Dialog", "<html><head/><body><p>Attention : cette opération efface toutes les données présentes dans la base. Si vous souhaitez conserver ces données, vous pouvez au préalable sauvegarder cette base dans un fichier externe à l\'aide du bouton &quot;Sauvegarder la base...&quot;. </p></body></html>", None))
        self.pushButtonInitDB.setText(_translate("Dialog", "(Ré)initialiser la base", None))
        self.pushButtonDelete.setText(_translate("Dialog", "Supprimer la base", None))
        self.groupBoxParam.setTitle(_translate("Dialog", "Paramètres de connexion à la base de données courante", None))
        self.label_194.setText(_translate("Dialog", "Mot de passe", None))
        self.lineEdit_port.setText(_translate("Dialog", "55432", None))
        self.label_4.setText(_translate("Dialog", "tempusaccess_", None))
        self.label_193.setText(_translate("Dialog", "Login", None))
        self.label_195.setText(_translate("Dialog", "Base", None))
        self.label_192.setText(_translate("Dialog", "Serveur", None))
        self.lineEdit_host.setToolTip(_translate("Dialog", "<html><head/><body><p>GTFSAnalyst utilise une base de données PostgreSQL-PostGIS pour le stockage des données et le calcul <br/>des indicateurs. Par défaut, elle est configurée pour être stockée localement sur la machine (installation PostgreSQL &quot;PGLite&quot;, base &quot;gtfsanalyst&quot; sur le port 55432 avec le nom d\'utilisateur de la session Windows et sans mot de passe).</p><p>Ce paramétrage peut être modifié ici, pour configurer le stockage de la base de données de l\'application<br/>sur un autre serveur ou dans une autre base.</p><p><br/></p></body></html>", None))
        self.lineEdit_host.setText(_translate("Dialog", "localhost", None))
        self.label.setText(_translate("Dialog", "Port", None))
        self.groupBoxStats.setTitle(_translate("Dialog", "Volumétrie de la base de données courante", None))
        self.labelRouteDataSize.setText(_translate("Dialog", "...", None))
        self.label_197.setToolTip(_translate("Dialog", "<html><head/><body><p>Cette fenêtre permet de surveiller l\'espace disque utilisé par la base de données. Afin d\'éviter de saturer le disque dur de la machine, il est peut être nécessaire de faire du vide quand l\'espace occupé par la base est trop important (suppression d\'indicateurs calculés, de données auxiliaires, etc.). </p></body></html>", None))
        self.label_197.setText(_translate("Dialog", "Taille base de données d\'offre TC", None))
        self.labelPTDataSize.setText(_translate("Dialog", "...", None))
        self.label_2.setText(_translate("Dialog", "Taille base de données auxiliaires", None))
        self.labelIndicDataSize.setText(_translate("Dialog", "...", None))
        self.labelAuxDataSize.setText(_translate("Dialog", "...", None))
        self.label_196.setText(_translate("Dialog", "Taille base de données d\'indicateurs", None))
        self.label_3.setText(_translate("Dialog", "Taille base de données d\'offre routière", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

