# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\GTFSAnalyst\forms\Ui_importSNCFOpenDataDialog.ui'
#
# Created: Mon Feb 26 11:30:48 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1038, 491)
        self.layoutWidget_2 = QtGui.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 1011, 464))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonGenererAppariement = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonGenererAppariement.sizePolicy().hasHeightForWidth())
        self.pushButtonGenererAppariement.setSizePolicy(sizePolicy)
        self.pushButtonGenererAppariement.setObjectName(_fromUtf8("pushButtonGenererAppariement"))
        self.gridLayout.addWidget(self.pushButtonGenererAppariement, 9, 3, 1, 1)
        self.labelSchemaStockage = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSchemaStockage.sizePolicy().hasHeightForWidth())
        self.labelSchemaStockage.setSizePolicy(sizePolicy)
        self.labelSchemaStockage.setWhatsThis(_fromUtf8(""))
        self.labelSchemaStockage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSchemaStockage.setObjectName(_fromUtf8("labelSchemaStockage"))
        self.gridLayout.addWidget(self.labelSchemaStockage, 0, 0, 1, 1)
        self.lineEditFichierNoeudsFerres = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditFichierNoeudsFerres.setObjectName(_fromUtf8("lineEditFichierNoeudsFerres"))
        self.gridLayout.addWidget(self.lineEditFichierNoeudsFerres, 6, 1, 1, 2)
        self.label = QtGui.QLabel(self.layoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.lineEditFichierIC = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFichierIC.sizePolicy().hasHeightForWidth())
        self.lineEditFichierIC.setSizePolicy(sizePolicy)
        self.lineEditFichierIC.setWhatsThis(_fromUtf8(""))
        self.lineEditFichierIC.setText(_fromUtf8(""))
        self.lineEditFichierIC.setObjectName(_fromUtf8("lineEditFichierIC"))
        self.gridLayout.addWidget(self.lineEditFichierIC, 1, 1, 1, 2)
        self.lineEditFichierTER = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFichierTER.sizePolicy().hasHeightForWidth())
        self.lineEditFichierTER.setSizePolicy(sizePolicy)
        self.lineEditFichierTER.setWhatsThis(_fromUtf8(""))
        self.lineEditFichierTER.setText(_fromUtf8(""))
        self.lineEditFichierTER.setObjectName(_fromUtf8("lineEditFichierTER"))
        self.gridLayout.addWidget(self.lineEditFichierTER, 0, 1, 1, 2)
        self.pushButtonChoisirVoiesFerrees = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonChoisirVoiesFerrees.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChoisirVoiesFerrees.sizePolicy().hasHeightForWidth())
        self.pushButtonChoisirVoiesFerrees.setSizePolicy(sizePolicy)
        self.pushButtonChoisirVoiesFerrees.setObjectName(_fromUtf8("pushButtonChoisirVoiesFerrees"))
        self.gridLayout.addWidget(self.pushButtonChoisirVoiesFerrees, 11, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 11, 0, 1, 1)
        self.pushButtonCorriger = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonCorriger.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCorriger.sizePolicy().hasHeightForWidth())
        self.pushButtonCorriger.setSizePolicy(sizePolicy)
        self.pushButtonCorriger.setObjectName(_fromUtf8("pushButtonCorriger"))
        self.gridLayout.addWidget(self.pushButtonCorriger, 12, 3, 1, 1)
        self.pushButtonChoisirTER = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonChoisirTER.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChoisirTER.sizePolicy().hasHeightForWidth())
        self.pushButtonChoisirTER.setSizePolicy(sizePolicy)
        self.pushButtonChoisirTER.setObjectName(_fromUtf8("pushButtonChoisirTER"))
        self.gridLayout.addWidget(self.pushButtonChoisirTER, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 2)
        self.lineEditFichierRefGares = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFichierRefGares.sizePolicy().hasHeightForWidth())
        self.lineEditFichierRefGares.setSizePolicy(sizePolicy)
        self.lineEditFichierRefGares.setWhatsThis(_fromUtf8(""))
        self.lineEditFichierRefGares.setText(_fromUtf8(""))
        self.lineEditFichierRefGares.setObjectName(_fromUtf8("lineEditFichierRefGares"))
        self.gridLayout.addWidget(self.lineEditFichierRefGares, 2, 1, 1, 2)
        self.line_2 = QtGui.QFrame(self.layoutWidget_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 10, 1, 1, 3)
        self.pushButtonChoisirIC = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonChoisirIC.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChoisirIC.sizePolicy().hasHeightForWidth())
        self.pushButtonChoisirIC.setSizePolicy(sizePolicy)
        self.pushButtonChoisirIC.setObjectName(_fromUtf8("pushButtonChoisirIC"))
        self.gridLayout.addWidget(self.pushButtonChoisirIC, 1, 3, 1, 1)
        self.lineEditFichierAppariementNoeudsFerres = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditFichierAppariementNoeudsFerres.setObjectName(_fromUtf8("lineEditFichierAppariementNoeudsFerres"))
        self.gridLayout.addWidget(self.lineEditFichierAppariementNoeudsFerres, 7, 1, 2, 2)
        self.label_4 = QtGui.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.lineEditFichierVoiesFerrees = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFichierVoiesFerrees.sizePolicy().hasHeightForWidth())
        self.lineEditFichierVoiesFerrees.setSizePolicy(sizePolicy)
        self.lineEditFichierVoiesFerrees.setWhatsThis(_fromUtf8(""))
        self.lineEditFichierVoiesFerrees.setText(_fromUtf8(""))
        self.lineEditFichierVoiesFerrees.setObjectName(_fromUtf8("lineEditFichierVoiesFerrees"))
        self.gridLayout.addWidget(self.lineEditFichierVoiesFerrees, 11, 1, 1, 2)
        self.labelSchemaStockage_3 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSchemaStockage_3.sizePolicy().hasHeightForWidth())
        self.labelSchemaStockage_3.setSizePolicy(sizePolicy)
        self.labelSchemaStockage_3.setWhatsThis(_fromUtf8(""))
        self.labelSchemaStockage_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSchemaStockage_3.setObjectName(_fromUtf8("labelSchemaStockage_3"))
        self.gridLayout.addWidget(self.labelSchemaStockage_3, 1, 0, 1, 1)
        self.line = QtGui.QFrame(self.layoutWidget_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 5, 0, 1, 4)
        self.pushButtonChoisirNoeudsFerres = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonChoisirNoeudsFerres.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChoisirNoeudsFerres.sizePolicy().hasHeightForWidth())
        self.pushButtonChoisirNoeudsFerres.setSizePolicy(sizePolicy)
        self.pushButtonChoisirNoeudsFerres.setObjectName(_fromUtf8("pushButtonChoisirNoeudsFerres"))
        self.gridLayout.addWidget(self.pushButtonChoisirNoeudsFerres, 6, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 3)
        self.checkBoxUtiliserTableInterne = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBoxUtiliserTableInterne.setObjectName(_fromUtf8("checkBoxUtiliserTableInterne"))
        self.gridLayout.addWidget(self.checkBoxUtiliserTableInterne, 9, 2, 1, 1)
        self.pushButtonChoisirRefGares = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonChoisirRefGares.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChoisirRefGares.sizePolicy().hasHeightForWidth())
        self.pushButtonChoisirRefGares.setSizePolicy(sizePolicy)
        self.pushButtonChoisirRefGares.setObjectName(_fromUtf8("pushButtonChoisirRefGares"))
        self.gridLayout.addWidget(self.pushButtonChoisirRefGares, 2, 3, 1, 1)
        self.pushButtonImporter = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonImporter.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonImporter.sizePolicy().hasHeightForWidth())
        self.pushButtonImporter.setSizePolicy(sizePolicy)
        self.pushButtonImporter.setObjectName(_fromUtf8("pushButtonImporter"))
        self.gridLayout.addWidget(self.pushButtonImporter, 3, 3, 2, 1)
        self.pushButtonChoisirAppariementNoeudsFerres = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonChoisirAppariementNoeudsFerres.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChoisirAppariementNoeudsFerres.sizePolicy().hasHeightForWidth())
        self.pushButtonChoisirAppariementNoeudsFerres.setSizePolicy(sizePolicy)
        self.pushButtonChoisirAppariementNoeudsFerres.setObjectName(_fromUtf8("pushButtonChoisirAppariementNoeudsFerres"))
        self.gridLayout.addWidget(self.pushButtonChoisirAppariementNoeudsFerres, 7, 3, 2, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 3)
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Importer des données GTFS open-data SNCF et leurs compléments", None))
        self.pushButtonGenererAppariement.setText(_translate("Dialog", "Générer automatiquement", None))
        self.labelSchemaStockage.setText(_translate("Dialog", "<html><head/><body><p>1. Source TER *<span style=\" font-size:6pt;\"> (open-data SNCF)</span></p></body></html>", None))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>3. Référentiel de gares <span style=\" font-size:6pt;\">facultatif (open-data SNCF)</span></p></body></html>", None))
        self.lineEditFichierIC.setToolTip(_translate("Dialog", "<html><head/><body><p>Le préfixe sera accolé aux identifiants des objets de la source (arrêts, services, lignes, etc.).</p><p>Il est obligatoire pour pouvoir charger une source et doit être différents des préfixes des sources déjà chargées dans la base (voir ci-dessous). </p></body></html>", None))
        self.lineEditFichierTER.setToolTip(_translate("Dialog", "<html><head/><body><p>Le préfixe sera accolé aux identifiants des objets de la source (arrêts, services, lignes, etc.).</p><p>Il est obligatoire pour pouvoir charger une source et doit être différents des préfixes des sources déjà chargées dans la base (voir ci-dessous). </p></body></html>", None))
        self.pushButtonChoisirVoiesFerrees.setToolTip(_translate("Dialog", "<html><head/><body><p>Le bouton n\'est accessible qu\'après avoir renseigné un préfixe pour la source. Le préfixe doit être différent de ceux des sources déjà importées (voir liste ci-dessous). </p><p>Attention : la source doit être un fichier .zip contenant directement les fichiers .txt, aucun dossier ne doit être inclus dans le fichier .zip. </p></body></html>", None))
        self.pushButtonChoisirVoiesFerrees.setText(_translate("Dialog", "Parcourir...", None))
        self.label_2.setText(_translate("Dialog", "4. Noeuds ferroviaires * (Route500)", None))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p>6. Tracé des lignes ferroviaires *<span style=\" font-size:6pt;\"> (Route500)</span></p></body></html>", None))
        self.pushButtonCorriger.setText(_translate("Dialog", "Importer et corriger", None))
        self.pushButtonChoisirTER.setToolTip(_translate("Dialog", "<html><head/><body><p>Le bouton n\'est accessible qu\'après avoir renseigné un préfixe pour la source. Le préfixe doit être différent de ceux des sources déjà importées (voir liste ci-dessous). </p><p>Attention : la source doit être un fichier .zip contenant directement les fichiers .txt, aucun dossier ne doit être inclus dans le fichier .zip. </p></body></html>", None))
        self.pushButtonChoisirTER.setText(_translate("Dialog", "Parcourir...", None))
        self.label_5.setText(_translate("Dialog", "OU", None))
        self.lineEditFichierRefGares.setToolTip(_translate("Dialog", "<html><head/><body><p>Le préfixe sera accolé aux identifiants des objets de la source (arrêts, services, lignes, etc.).</p><p>Il est obligatoire pour pouvoir charger une source et doit être différents des préfixes des sources déjà chargées dans la base (voir ci-dessous). </p></body></html>", None))
        self.pushButtonChoisirIC.setToolTip(_translate("Dialog", "<html><head/><body><p>Le bouton n\'est accessible qu\'après avoir renseigné un préfixe pour la source. Le préfixe doit être différent de ceux des sources déjà importées (voir liste ci-dessous). </p><p>Attention : la source doit être un fichier .zip contenant directement les fichiers .txt, aucun dossier ne doit être inclus dans le fichier .zip. </p></body></html>", None))
        self.pushButtonChoisirIC.setText(_translate("Dialog", "Parcourir...", None))
        self.label_4.setText(_translate("Dialog", "5. Fichier d\'appariement noeuds fer", None))
        self.lineEditFichierVoiesFerrees.setToolTip(_translate("Dialog", "<html><head/><body><p>Le préfixe sera accolé aux identifiants des objets de la source (arrêts, services, lignes, etc.).</p><p>Il est obligatoire pour pouvoir charger une source et doit être différents des préfixes des sources déjà chargées dans la base (voir ci-dessous). </p></body></html>", None))
        self.labelSchemaStockage_3.setText(_translate("Dialog", "<html><head/><body><p>2. Source Intercités *<span style=\" font-size:6pt;\"> (open-data SNCF)</span></p></body></html>", None))
        self.pushButtonChoisirNoeudsFerres.setToolTip(_translate("Dialog", "<html><head/><body><p>Le bouton n\'est accessible qu\'après avoir renseigné un préfixe pour la source. Le préfixe doit être différent de ceux des sources déjà importées (voir liste ci-dessous). </p><p>Attention : la source doit être un fichier .zip contenant directement les fichiers .txt, aucun dossier ne doit être inclus dans le fichier .zip. </p></body></html>", None))
        self.pushButtonChoisirNoeudsFerres.setText(_translate("Dialog", "Parcourir...", None))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:6pt; font-style:italic;\">Pour utiliser un référentiel d\'arrêts en complément du référentiel de gares Open-Data SNCF, </span></p></body></html>", None))
        self.checkBoxUtiliserTableInterne.setText(_translate("Dialog", "Utiliser la table interne", None))
        self.pushButtonChoisirRefGares.setToolTip(_translate("Dialog", "<html><head/><body><p>Le bouton n\'est accessible qu\'après avoir renseigné un préfixe pour la source. Le préfixe doit être différent de ceux des sources déjà importées (voir liste ci-dessous). </p><p>Attention : la source doit être un fichier .zip contenant directement les fichiers .txt, aucun dossier ne doit être inclus dans le fichier .zip. </p></body></html>", None))
        self.pushButtonChoisirRefGares.setText(_translate("Dialog", "Parcourir...", None))
        self.pushButtonImporter.setText(_translate("Dialog", "Importer et fusionner", None))
        self.pushButtonChoisirAppariementNoeudsFerres.setToolTip(_translate("Dialog", "<html><head/><body><p>Le bouton n\'est accessible qu\'après avoir renseigné un préfixe pour la source. Le préfixe doit être différent de ceux des sources déjà importées (voir liste ci-dessous). </p><p>Attention : la source doit être un fichier .zip contenant directement les fichiers .txt, aucun dossier ne doit être inclus dans le fichier .zip. </p></body></html>", None))
        self.pushButtonChoisirAppariementNoeudsFerres.setText(_translate("Dialog", "Parcourir...", None))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:6pt; font-style:italic;\">le charger préalablement à l\'opération d\'import des fichiers Open-Data SNCF.</span></p></body></html>", None))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:6pt;\">facultatif (open-data SNCF / Route500)</span></p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

