# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_manage_indicators_dialog.ui'
#
# Created: Thu Nov 22 13:16:57 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(658, 587)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(550, 530, 81, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.toolBoxDisplay = QtGui.QToolBox(Dialog)
        self.toolBoxDisplay.setGeometry(QtCore.QRect(10, 10, 631, 241))
        self.toolBoxDisplay.setObjectName(_fromUtf8("toolBoxDisplay"))
        self.page_8 = QtGui.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.layoutWidget = QtGui.QWidget(self.page_8)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 0, 601, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.labelReq = QtGui.QLabel(self.layoutWidget)
        self.labelReq.setEnabled(True)
        self.labelReq.setObjectName(_fromUtf8("labelReq"))
        self.horizontalLayout_11.addWidget(self.labelReq)
        self.comboBoxReq = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxReq.sizePolicy().hasHeightForWidth())
        self.comboBoxReq.setSizePolicy(sizePolicy)
        self.comboBoxReq.setEditable(True)
        self.comboBoxReq.setObjectName(_fromUtf8("comboBoxReq"))
        self.horizontalLayout_11.addWidget(self.comboBoxReq)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.pushButtonReqRename = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonReqRename.setObjectName(_fromUtf8("pushButtonReqRename"))
        self.horizontalLayout_11.addWidget(self.pushButtonReqRename)
        self.pushButtonReqDelete = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonReqDelete.setEnabled(True)
        self.pushButtonReqDelete.setObjectName(_fromUtf8("pushButtonReqDelete"))
        self.horizontalLayout_11.addWidget(self.pushButtonReqDelete)
        self.layoutWidget_2 = QtGui.QWidget(self.page_8)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 40, 601, 73))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_17 = QtGui.QLabel(self.layoutWidget_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        self.textEditComments = QtGui.QTextEdit(self.layoutWidget_2)
        self.textEditComments.setObjectName(_fromUtf8("textEditComments"))
        self.horizontalLayout_12.addWidget(self.textEditComments)
        self.pushButtonSaveComments = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonSaveComments.setObjectName(_fromUtf8("pushButtonSaveComments"))
        self.horizontalLayout_12.addWidget(self.pushButtonSaveComments)
        self.toolBoxDisplay.addItem(self.page_8, _fromUtf8(""))
        self.page_9 = QtGui.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 631, 187))
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.layoutWidget_7 = QtGui.QWidget(self.page_9)
        self.layoutWidget_7.setGeometry(QtCore.QRect(20, 0, 601, 31))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.labelDerivedIndic = QtGui.QLabel(self.layoutWidget_7)
        self.labelDerivedIndic.setEnabled(True)
        self.labelDerivedIndic.setObjectName(_fromUtf8("labelDerivedIndic"))
        self.horizontalLayout_15.addWidget(self.labelDerivedIndic)
        self.comboBoxDerivedRep = QtGui.QComboBox(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDerivedRep.sizePolicy().hasHeightForWidth())
        self.comboBoxDerivedRep.setSizePolicy(sizePolicy)
        self.comboBoxDerivedRep.setEditable(True)
        self.comboBoxDerivedRep.setObjectName(_fromUtf8("comboBoxDerivedRep"))
        self.horizontalLayout_15.addWidget(self.comboBoxDerivedRep)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.pushButtonDerivedRepRename = QtGui.QPushButton(self.layoutWidget_7)
        self.pushButtonDerivedRepRename.setObjectName(_fromUtf8("pushButtonDerivedRepRename"))
        self.horizontalLayout_15.addWidget(self.pushButtonDerivedRepRename)
        self.pushButtonDerivedRepDelete = QtGui.QPushButton(self.layoutWidget_7)
        self.pushButtonDerivedRepDelete.setEnabled(True)
        self.pushButtonDerivedRepDelete.setObjectName(_fromUtf8("pushButtonDerivedRepDelete"))
        self.horizontalLayout_15.addWidget(self.pushButtonDerivedRepDelete)
        self.groupBoxParamDerivedRep = QtGui.QGroupBox(self.page_9)
        self.groupBoxParamDerivedRep.setGeometry(QtCore.QRect(10, 40, 611, 131))
        self.groupBoxParamDerivedRep.setObjectName(_fromUtf8("groupBoxParamDerivedRep"))
        self.layoutWidget_6 = QtGui.QWidget(self.groupBoxParamDerivedRep)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 20, 591, 96))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.gridLayout_12 = QtGui.QGridLayout(self.layoutWidget_6)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.doubleSpinBoxRepParam = QtGui.QDoubleSpinBox(self.layoutWidget_6)
        self.doubleSpinBoxRepParam.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinBoxRepParam.setDecimals(3)
        self.doubleSpinBoxRepParam.setProperty("value", 0.0)
        self.doubleSpinBoxRepParam.setObjectName(_fromUtf8("doubleSpinBoxRepParam"))
        self.gridLayout_12.addWidget(self.doubleSpinBoxRepParam, 2, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget_6)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_12.addWidget(self.label_12, 0, 3, 1, 1)
        self.spinBoxDerivedRepClasses = QtGui.QSpinBox(self.layoutWidget_6)
        self.spinBoxDerivedRepClasses.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBoxDerivedRepClasses.setMaximum(999)
        self.spinBoxDerivedRepClasses.setProperty("value", 20)
        self.spinBoxDerivedRepClasses.setObjectName(_fromUtf8("spinBoxDerivedRepClasses"))
        self.gridLayout_12.addWidget(self.spinBoxDerivedRepClasses, 0, 4, 1, 1)
        self.spinBoxDerivedRepIndicMaxValue = QtGui.QSpinBox(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxDerivedRepIndicMaxValue.sizePolicy().hasHeightForWidth())
        self.spinBoxDerivedRepIndicMaxValue.setSizePolicy(sizePolicy)
        self.spinBoxDerivedRepIndicMaxValue.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBoxDerivedRepIndicMaxValue.setMaximum(1000000)
        self.spinBoxDerivedRepIndicMaxValue.setObjectName(_fromUtf8("spinBoxDerivedRepIndicMaxValue"))
        self.gridLayout_12.addWidget(self.spinBoxDerivedRepIndicMaxValue, 2, 1, 1, 1)
        self.comboBoxDerivedRepIndic = QtGui.QComboBox(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDerivedRepIndic.sizePolicy().hasHeightForWidth())
        self.comboBoxDerivedRepIndic.setSizePolicy(sizePolicy)
        self.comboBoxDerivedRepIndic.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxDerivedRepIndic.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBoxDerivedRepIndic.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxDerivedRepIndic.setObjectName(_fromUtf8("comboBoxDerivedRepIndic"))
        self.gridLayout_12.addWidget(self.comboBoxDerivedRepIndic, 0, 1, 1, 2)
        self.label_25 = QtGui.QLabel(self.layoutWidget_6)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_12.addWidget(self.label_25, 1, 3, 1, 1)
        self.pushButtonDerivedRepGenerate = QtGui.QPushButton(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDerivedRepGenerate.sizePolicy().hasHeightForWidth())
        self.pushButtonDerivedRepGenerate.setSizePolicy(sizePolicy)
        self.pushButtonDerivedRepGenerate.setBaseSize(QtCore.QSize(100, 0))
        self.pushButtonDerivedRepGenerate.setObjectName(_fromUtf8("pushButtonDerivedRepGenerate"))
        self.gridLayout_12.addWidget(self.pushButtonDerivedRepGenerate, 1, 5, 1, 1)
        self.spinBoxDerivedRepIndicMinValue = QtGui.QSpinBox(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxDerivedRepIndicMinValue.sizePolicy().hasHeightForWidth())
        self.spinBoxDerivedRepIndicMinValue.setSizePolicy(sizePolicy)
        self.spinBoxDerivedRepIndicMinValue.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBoxDerivedRepIndicMinValue.setMaximum(1000000)
        self.spinBoxDerivedRepIndicMinValue.setObjectName(_fromUtf8("spinBoxDerivedRepIndicMinValue"))
        self.gridLayout_12.addWidget(self.spinBoxDerivedRepIndicMinValue, 1, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.layoutWidget_6)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_12.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.layoutWidget_6)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_12.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget_6)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_12.addWidget(self.label_26, 2, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_12.addWidget(self.label_15, 0, 0, 1, 1)
        self.comboBoxRepMeth = QtGui.QComboBox(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxRepMeth.sizePolicy().hasHeightForWidth())
        self.comboBoxRepMeth.setSizePolicy(sizePolicy)
        self.comboBoxRepMeth.setObjectName(_fromUtf8("comboBoxRepMeth"))
        self.gridLayout_12.addWidget(self.comboBoxRepMeth, 1, 4, 1, 1)
        self.toolBoxDisplay.addItem(self.page_9, _fromUtf8(""))
        self.groupBoxGeoQuery = QtGui.QGroupBox(Dialog)
        self.groupBoxGeoQuery.setGeometry(QtCore.QRect(10, 280, 631, 191))
        self.groupBoxGeoQuery.setObjectName(_fromUtf8("groupBoxGeoQuery"))
        self.groupBoxSize = QtGui.QGroupBox(self.groupBoxGeoQuery)
        self.groupBoxSize.setGeometry(QtCore.QRect(10, 20, 361, 161))
        self.groupBoxSize.setObjectName(_fromUtf8("groupBoxSize"))
        self.layoutWidget_3 = QtGui.QWidget(self.groupBoxSize)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 30, 341, 122))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_11 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButtonMapUnit = QtGui.QRadioButton(self.layoutWidget_3)
        self.radioButtonMapUnit.setObjectName(_fromUtf8("radioButtonMapUnit"))
        self.verticalLayout.addWidget(self.radioButtonMapUnit)
        self.radioButtonScreenUnit = QtGui.QRadioButton(self.layoutWidget_3)
        self.radioButtonScreenUnit.setChecked(True)
        self.radioButtonScreenUnit.setObjectName(_fromUtf8("radioButtonScreenUnit"))
        self.verticalLayout.addWidget(self.radioButtonScreenUnit)
        self.gridLayout_11.addLayout(self.verticalLayout, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_11.addWidget(self.label_10, 0, 0, 1, 1)
        self.comboBoxSizeIndic = QtGui.QComboBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSizeIndic.sizePolicy().hasHeightForWidth())
        self.comboBoxSizeIndic.setSizePolicy(sizePolicy)
        self.comboBoxSizeIndic.setObjectName(_fromUtf8("comboBoxSizeIndic"))
        self.gridLayout_11.addWidget(self.comboBoxSizeIndic, 0, 1, 1, 2)
        self.doubleSpinBoxSize = QtGui.QDoubleSpinBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxSize.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxSize.setSizePolicy(sizePolicy)
        self.doubleSpinBoxSize.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinBoxSize.setDecimals(0)
        self.doubleSpinBoxSize.setMaximum(1000000.0)
        self.doubleSpinBoxSize.setProperty("value", 20.0)
        self.doubleSpinBoxSize.setObjectName(_fromUtf8("doubleSpinBoxSize"))
        self.gridLayout_11.addWidget(self.doubleSpinBoxSize, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_11.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget_3)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_11.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget_3)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_11.addWidget(self.label_18, 1, 0, 1, 1)
        self.spinBoxSizeIndicMaxValue = QtGui.QSpinBox(self.layoutWidget_3)
        self.spinBoxSizeIndicMaxValue.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBoxSizeIndicMaxValue.setMaximum(1000000)
        self.spinBoxSizeIndicMaxValue.setObjectName(_fromUtf8("spinBoxSizeIndicMaxValue"))
        self.gridLayout_11.addWidget(self.spinBoxSizeIndicMaxValue, 2, 1, 1, 1)
        self.spinBoxSizeIndicMinValue = QtGui.QSpinBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxSizeIndicMinValue.sizePolicy().hasHeightForWidth())
        self.spinBoxSizeIndicMinValue.setSizePolicy(sizePolicy)
        self.spinBoxSizeIndicMinValue.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBoxSizeIndicMinValue.setMaximum(1000000)
        self.spinBoxSizeIndicMinValue.setObjectName(_fromUtf8("spinBoxSizeIndicMinValue"))
        self.gridLayout_11.addWidget(self.spinBoxSizeIndicMinValue, 1, 1, 1, 1)
        self.groupBoxColor = QtGui.QGroupBox(self.groupBoxGeoQuery)
        self.groupBoxColor.setGeometry(QtCore.QRect(390, 20, 231, 161))
        self.groupBoxColor.setObjectName(_fromUtf8("groupBoxColor"))
        self.layoutWidget_9 = QtGui.QWidget(self.groupBoxColor)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 30, 211, 81))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget_9)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_9)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_9.addWidget(self.label_6, 0, 0, 1, 1)
        self.comboBoxColorIndic = QtGui.QComboBox(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxColorIndic.sizePolicy().hasHeightForWidth())
        self.comboBoxColorIndic.setSizePolicy(sizePolicy)
        self.comboBoxColorIndic.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxColorIndic.setObjectName(_fromUtf8("comboBoxColorIndic"))
        self.gridLayout_9.addWidget(self.comboBoxColorIndic, 0, 1, 1, 2)
        self.label_21 = QtGui.QLabel(self.layoutWidget_9)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_9.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget_9)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_9.addWidget(self.label_20, 2, 0, 1, 1)
        self.spinBoxColorIndicMaxValue = QtGui.QSpinBox(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxColorIndicMaxValue.sizePolicy().hasHeightForWidth())
        self.spinBoxColorIndicMaxValue.setSizePolicy(sizePolicy)
        self.spinBoxColorIndicMaxValue.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spinBoxColorIndicMaxValue.setMaximum(1000000)
        self.spinBoxColorIndicMaxValue.setObjectName(_fromUtf8("spinBoxColorIndicMaxValue"))
        self.gridLayout_9.addWidget(self.spinBoxColorIndicMaxValue, 2, 1, 1, 2)
        self.spinBoxColorIndicMinValue = QtGui.QSpinBox(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxColorIndicMinValue.sizePolicy().hasHeightForWidth())
        self.spinBoxColorIndicMinValue.setSizePolicy(sizePolicy)
        self.spinBoxColorIndicMinValue.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spinBoxColorIndicMinValue.setMaximum(1000000)
        self.spinBoxColorIndicMinValue.setObjectName(_fromUtf8("spinBoxColorIndicMinValue"))
        self.gridLayout_9.addWidget(self.spinBoxColorIndicMinValue, 1, 1, 1, 2)
        self.layoutWidget_4 = QtGui.QWidget(Dialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 490, 591, 29))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBoxPathID = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBoxPathID.setMaximumSize(QtCore.QSize(60, 16777215))
        self.comboBoxPathID.setObjectName(_fromUtf8("comboBoxPathID"))
        self.horizontalLayout_2.addWidget(self.comboBoxPathID)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonReqDisplay = QtGui.QPushButton(self.layoutWidget_4)
        self.pushButtonReqDisplay.setEnabled(True)
        self.pushButtonReqDisplay.setObjectName(_fromUtf8("pushButtonReqDisplay"))
        self.horizontalLayout_2.addWidget(self.pushButtonReqDisplay)
        self.layoutWidget_5 = QtGui.QWidget(Dialog)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 540, 521, 22))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEditCommand = QtGui.QLineEdit(self.layoutWidget_5)
        self.lineEditCommand.setEnabled(False)
        self.lineEditCommand.setObjectName(_fromUtf8("lineEditCommand"))
        self.horizontalLayout.addWidget(self.lineEditCommand)

        self.retranslateUi(Dialog)
        self.toolBoxDisplay.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Gestion des calculs stockés", None))
        self.labelReq.setText(_translate("Dialog", "Couches", None))
        self.pushButtonReqRename.setToolTip(_translate("Dialog", "<html><head/><body><p>Renommer la requête dans la base de données</p></body></html>", None))
        self.pushButtonReqRename.setText(_translate("Dialog", "Renommer", None))
        self.pushButtonReqDelete.setToolTip(_translate("Dialog", "<html><head/><body><p>Supprimer la requête stockée de la base de donnée (opération non-annulable)</p></body></html>", None))
        self.pushButtonReqDelete.setText(_translate("Dialog", "Supprimer", None))
        self.label_17.setText(_translate("Dialog", "Commentaires", None))
        self.pushButtonSaveComments.setToolTip(_translate("Dialog", "<html><head/><body><p>Sauvegarder les commentaires de la requête dans la base de données</p></body></html>", None))
        self.pushButtonSaveComments.setText(_translate("Dialog", "Enregistrer", None))
        self.toolBoxDisplay.setItemText(self.toolBoxDisplay.indexOf(self.page_8), _translate("Dialog", "Requêtes stockées", None))
        self.labelDerivedIndic.setText(_translate("Dialog", "Couches", None))
        self.pushButtonDerivedRepRename.setToolTip(_translate("Dialog", "<html><head/><body><p>Renommer la requête dans la base de données</p></body></html>", None))
        self.pushButtonDerivedRepRename.setText(_translate("Dialog", "Renommer", None))
        self.pushButtonDerivedRepDelete.setToolTip(_translate("Dialog", "<html><head/><body><p>Supprimer la requête stockée de la base de donnée (opération non-annulable)</p></body></html>", None))
        self.pushButtonDerivedRepDelete.setText(_translate("Dialog", "Supprimer", None))
        self.groupBoxParamDerivedRep.setTitle(_translate("Dialog", "Paramètres de génération d\'une isosurface", None))
        self.label_12.setText(_translate("Dialog", "Nombre de classes", None))
        self.comboBoxDerivedRepIndic.setToolTip(_translate("Dialog", "<html><head/><body><p>Choisir l\'indicateur à cartographier par des variations de couleurs des symboles</p></body></html>", None))
        self.label_25.setText(_translate("Dialog", "Méthode", None))
        self.pushButtonDerivedRepGenerate.setText(_translate("Dialog", "Générer", None))
        self.label_28.setText(_translate("Dialog", "Valeur max", None))
        self.label_27.setText(_translate("Dialog", "Valeur min", None))
        self.label_26.setText(_translate("Dialog", "Paramètre", None))
        self.label_15.setText(_translate("Dialog", "Indicateur", None))
        self.toolBoxDisplay.setItemText(self.toolBoxDisplay.indexOf(self.page_9), _translate("Dialog", "Isosurfaces dérivées de la requête stockée courante", None))
        self.groupBoxGeoQuery.setTitle(_translate("Dialog", "Style d\'affichage des objets", None))
        self.groupBoxSize.setTitle(_translate("Dialog", "Taille", None))
        self.radioButtonMapUnit.setToolTip(_translate("Dialog", "<html><head/><body><p>&quot;Unité de la carte&quot; implique une définition de la taille de l\'indicateur en mètres. La taille du symbole le représentant sera d\'autant plus importante que le zoom est fort. </p></body></html>", None))
        self.radioButtonMapUnit.setText(_translate("Dialog", "Unité de la carte (m)", None))
        self.radioButtonScreenUnit.setToolTip(_translate("Dialog", "<html><head/><body><p>&quot;Unité de la carte&quot; implique une définition de la taille de l\'indicateur en millimètres. La taille du symbole le représentant sera stable à tous les niveaux de zoom. Pour des zooms très faibles, une faible lisibilité est possible en raison de superposition des symboles. </p></body></html>", None))
        self.radioButtonScreenUnit.setText(_translate("Dialog", "Unité de l\'écran (mm)", None))
        self.label_10.setText(_translate("Dialog", "Indicateur", None))
        self.comboBoxSizeIndic.setToolTip(_translate("Dialog", "<html><head/><body><p>Choisir l\'indicateur à cartographier par des variations de taille des symboles</p></body></html>", None))
        self.label_3.setText(_translate("Dialog", "Taille max ", None))
        self.label_19.setText(_translate("Dialog", "Valeur associée à la taille max", None))
        self.label_18.setText(_translate("Dialog", "Valeur associée à la taille 0", None))
        self.groupBoxColor.setTitle(_translate("Dialog", "Dégradé de couleurs", None))
        self.label_6.setText(_translate("Dialog", "Indicateur", None))
        self.comboBoxColorIndic.setToolTip(_translate("Dialog", "<html><head/><body><p>Choisir l\'indicateur à cartographier par des variations de couleurs des symboles</p></body></html>", None))
        self.label_21.setText(_translate("Dialog", "Valeur min", None))
        self.label_20.setText(_translate("Dialog", "Valeur max", None))
        self.label_4.setText(_translate("Dialog", "Filtrer les chemins : afficher l\'identifiant", None))
        self.pushButtonReqDisplay.setToolTip(_translate("Dialog", "<html><head/><body><p>Cartographier les indicateurs choisis</p></body></html>", None))
        self.pushButtonReqDisplay.setText(_translate("Dialog", "Ajouter la couche", None))
        self.label_5.setText(_translate("Dialog", "Dernière commande exécutée", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

