# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aurelie-p.bousquet\.qgis2\python\plugins\TempusAccess\forms\Ui_TempusAccessDockWidget.ui'
#
# Created: Wed Oct 31 09:08:34 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TempusAccessDockWidget(object):
    def setupUi(self, TempusAccessDockWidget):
        TempusAccessDockWidget.setObjectName(_fromUtf8("TempusAccessDockWidget"))
        TempusAccessDockWidget.resize(658, 620)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.Tabs = QtGui.QTabWidget(self.dockWidgetContents)
        self.Tabs.setEnabled(True)
        self.Tabs.setGeometry(QtCore.QRect(0, 0, 651, 551))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        self.Tabs.setAutoFillBackground(False)
        self.Tabs.setObjectName(_fromUtf8("Tabs"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBoxObjType = QtGui.QGroupBox(self.tab_5)
        self.groupBoxObjType.setEnabled(True)
        self.groupBoxObjType.setGeometry(QtCore.QRect(10, 10, 341, 61))
        self.groupBoxObjType.setObjectName(_fromUtf8("groupBoxObjType"))
        self.comboBoxObjType = QtGui.QComboBox(self.groupBoxObjType)
        self.comboBoxObjType.setGeometry(QtCore.QRect(20, 30, 311, 21))
        self.comboBoxObjType.setObjectName(_fromUtf8("comboBoxObjType"))
        self.groupBoxPerimetre = QtGui.QGroupBox(self.tab_5)
        self.groupBoxPerimetre.setEnabled(True)
        self.groupBoxPerimetre.setGeometry(QtCore.QRect(10, 450, 621, 71))
        self.groupBoxPerimetre.setObjectName(_fromUtf8("groupBoxPerimetre"))
        self.layoutWidget = QtGui.QWidget(self.groupBoxPerimetre)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 601, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.comboBoxArea = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxArea.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxArea.sizePolicy().hasHeightForWidth())
        self.comboBoxArea.setSizePolicy(sizePolicy)
        self.comboBoxArea.setObjectName(_fromUtf8("comboBoxArea"))
        self.gridLayout_4.addWidget(self.comboBoxArea, 0, 4, 1, 1)
        self.labelPerimeterType = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPerimeterType.sizePolicy().hasHeightForWidth())
        self.labelPerimeterType.setSizePolicy(sizePolicy)
        self.labelPerimeterType.setObjectName(_fromUtf8("labelPerimeterType"))
        self.gridLayout_4.addWidget(self.labelPerimeterType, 0, 0, 1, 1)
        self.labelPerimeter = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPerimeter.sizePolicy().hasHeightForWidth())
        self.labelPerimeter.setSizePolicy(sizePolicy)
        self.labelPerimeter.setObjectName(_fromUtf8("labelPerimeter"))
        self.gridLayout_4.addWidget(self.labelPerimeter, 0, 3, 1, 1)
        self.comboBoxAreaType = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxAreaType.sizePolicy().hasHeightForWidth())
        self.comboBoxAreaType.setSizePolicy(sizePolicy)
        self.comboBoxAreaType.setObjectName(_fromUtf8("comboBoxAreaType"))
        self.gridLayout_4.addWidget(self.comboBoxAreaType, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.groupBoxIndicators = QtGui.QGroupBox(self.tab_5)
        self.groupBoxIndicators.setGeometry(QtCore.QRect(360, 10, 271, 231))
        self.groupBoxIndicators.setObjectName(_fromUtf8("groupBoxIndicators"))
        self.listViewIndic = QtGui.QListView(self.groupBoxIndicators)
        self.listViewIndic.setEnabled(True)
        self.listViewIndic.setGeometry(QtCore.QRect(10, 30, 241, 181))
        self.listViewIndic.setMaximumSize(QtCore.QSize(16777215, 300))
        self.listViewIndic.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewIndic.setObjectName(_fromUtf8("listViewIndic"))
        self.groupBoxPaths = QtGui.QGroupBox(self.tab_5)
        self.groupBoxPaths.setGeometry(QtCore.QRect(10, 80, 341, 361))
        self.groupBoxPaths.setObjectName(_fromUtf8("groupBoxPaths"))
        self.layoutWidget_5 = QtGui.QWidget(self.groupBoxPaths)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 30, 311, 22))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_33 = QtGui.QLabel(self.layoutWidget_5)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_9.addWidget(self.label_33)
        self.comboBoxNodeType = QtGui.QComboBox(self.layoutWidget_5)
        self.comboBoxNodeType.setObjectName(_fromUtf8("comboBoxNodeType"))
        self.horizontalLayout_9.addWidget(self.comboBoxNodeType)
        self.toolBoxPaths = QtGui.QToolBox(self.groupBoxPaths)
        self.toolBoxPaths.setEnabled(True)
        self.toolBoxPaths.setGeometry(QtCore.QRect(10, 100, 321, 251))
        self.toolBoxPaths.setObjectName(_fromUtf8("toolBoxPaths"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 321, 170))
        self.page.setObjectName(_fromUtf8("page"))
        self.layoutWidget_3 = QtGui.QWidget(self.page)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 0, 301, 95))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBoxDest = QtGui.QComboBox(self.layoutWidget_3)
        self.comboBoxDest.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDest.sizePolicy().hasHeightForWidth())
        self.comboBoxDest.setSizePolicy(sizePolicy)
        self.comboBoxDest.setObjectName(_fromUtf8("comboBoxDest"))
        self.gridLayout.addWidget(self.comboBoxDest, 2, 1, 1, 1)
        self.labelFromNode = QtGui.QLabel(self.layoutWidget_3)
        self.labelFromNode.setEnabled(True)
        self.labelFromNode.setObjectName(_fromUtf8("labelFromNode"))
        self.gridLayout.addWidget(self.labelFromNode, 0, 0, 1, 1)
        self.pushButtonChooseOrigOnMap = QtGui.QPushButton(self.layoutWidget_3)
        self.pushButtonChooseOrigOnMap.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChooseOrigOnMap.sizePolicy().hasHeightForWidth())
        self.pushButtonChooseOrigOnMap.setSizePolicy(sizePolicy)
        self.pushButtonChooseOrigOnMap.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonChooseOrigOnMap.setObjectName(_fromUtf8("pushButtonChooseOrigOnMap"))
        self.gridLayout.addWidget(self.pushButtonChooseOrigOnMap, 0, 2, 1, 1)
        self.labelToNode = QtGui.QLabel(self.layoutWidget_3)
        self.labelToNode.setEnabled(True)
        self.labelToNode.setObjectName(_fromUtf8("labelToNode"))
        self.gridLayout.addWidget(self.labelToNode, 2, 0, 1, 1)
        self.pushButtonChooseDestOnMap = QtGui.QPushButton(self.layoutWidget_3)
        self.pushButtonChooseDestOnMap.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChooseDestOnMap.sizePolicy().hasHeightForWidth())
        self.pushButtonChooseDestOnMap.setSizePolicy(sizePolicy)
        self.pushButtonChooseDestOnMap.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonChooseDestOnMap.setObjectName(_fromUtf8("pushButtonChooseDestOnMap"))
        self.gridLayout.addWidget(self.pushButtonChooseDestOnMap, 2, 2, 1, 1)
        self.comboBoxOrig = QtGui.QComboBox(self.layoutWidget_3)
        self.comboBoxOrig.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxOrig.sizePolicy().hasHeightForWidth())
        self.comboBoxOrig.setSizePolicy(sizePolicy)
        self.comboBoxOrig.setObjectName(_fromUtf8("comboBoxOrig"))
        self.gridLayout.addWidget(self.comboBoxOrig, 0, 1, 1, 1)
        self.pushButtonInvertOD = QtGui.QPushButton(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonInvertOD.sizePolicy().hasHeightForWidth())
        self.pushButtonInvertOD.setSizePolicy(sizePolicy)
        self.pushButtonInvertOD.setObjectName(_fromUtf8("pushButtonInvertOD"))
        self.gridLayout.addWidget(self.pushButtonInvertOD, 1, 2, 1, 1)
        self.toolBoxPaths.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 321, 170))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.layoutWidget1 = QtGui.QWidget(self.page_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 311, 29))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.comboBoxPathsTreeOD = QtGui.QComboBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPathsTreeOD.sizePolicy().hasHeightForWidth())
        self.comboBoxPathsTreeOD.setSizePolicy(sizePolicy)
        self.comboBoxPathsTreeOD.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxPathsTreeOD.setObjectName(_fromUtf8("comboBoxPathsTreeOD"))
        self.comboBoxPathsTreeOD.addItem(_fromUtf8(""))
        self.comboBoxPathsTreeOD.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBoxPathsTreeOD)
        self.comboBoxPathsTreeRootNode = QtGui.QComboBox(self.layoutWidget1)
        self.comboBoxPathsTreeRootNode.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPathsTreeRootNode.sizePolicy().hasHeightForWidth())
        self.comboBoxPathsTreeRootNode.setSizePolicy(sizePolicy)
        self.comboBoxPathsTreeRootNode.setObjectName(_fromUtf8("comboBoxPathsTreeRootNode"))
        self.horizontalLayout_6.addWidget(self.comboBoxPathsTreeRootNode)
        self.pushButtonChoosePathsTreeRootOnMap = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonChoosePathsTreeRootOnMap.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChoosePathsTreeRootOnMap.sizePolicy().hasHeightForWidth())
        self.pushButtonChoosePathsTreeRootOnMap.setSizePolicy(sizePolicy)
        self.pushButtonChoosePathsTreeRootOnMap.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonChoosePathsTreeRootOnMap.setObjectName(_fromUtf8("pushButtonChoosePathsTreeRootOnMap"))
        self.horizontalLayout_6.addWidget(self.pushButtonChoosePathsTreeRootOnMap)
        self.toolBoxPaths.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 321, 170))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.layoutWidget_10 = QtGui.QWidget(self.page_3)
        self.layoutWidget_10.setGeometry(QtCore.QRect(10, 0, 311, 151))
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget_10)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButtonRemovePathsTreesRoots = QtGui.QPushButton(self.layoutWidget_10)
        self.pushButtonRemovePathsTreesRoots.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemovePathsTreesRoots.sizePolicy().hasHeightForWidth())
        self.pushButtonRemovePathsTreesRoots.setSizePolicy(sizePolicy)
        self.pushButtonRemovePathsTreesRoots.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonRemovePathsTreesRoots.setObjectName(_fromUtf8("pushButtonRemovePathsTreesRoots"))
        self.gridLayout_2.addWidget(self.pushButtonRemovePathsTreesRoots, 1, 3, 1, 1)
        self.pushButtonChoosePathsTreesRootsOnMap = QtGui.QPushButton(self.layoutWidget_10)
        self.pushButtonChoosePathsTreesRootsOnMap.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChoosePathsTreesRootsOnMap.sizePolicy().hasHeightForWidth())
        self.pushButtonChoosePathsTreesRootsOnMap.setSizePolicy(sizePolicy)
        self.pushButtonChoosePathsTreesRootsOnMap.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonChoosePathsTreesRootsOnMap.setObjectName(_fromUtf8("pushButtonChoosePathsTreesRootsOnMap"))
        self.gridLayout_2.addWidget(self.pushButtonChoosePathsTreesRootsOnMap, 0, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_9 = QtGui.QLabel(self.layoutWidget_10)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.comboBoxNodeAg = QtGui.QComboBox(self.layoutWidget_10)
        self.comboBoxNodeAg.setObjectName(_fromUtf8("comboBoxNodeAg"))
        self.horizontalLayout.addWidget(self.comboBoxNodeAg)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 4)
        self.listViewNodes = QtGui.QListView(self.layoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewNodes.sizePolicy().hasHeightForWidth())
        self.listViewNodes.setSizePolicy(sizePolicy)
        self.listViewNodes.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listViewNodes.setAlternatingRowColors(True)
        self.listViewNodes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewNodes.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listViewNodes.setObjectName(_fromUtf8("listViewNodes"))
        self.gridLayout_2.addWidget(self.listViewNodes, 0, 2, 3, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 3, 1, 1)
        self.comboBoxCombPathsTreesOD = QtGui.QComboBox(self.layoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCombPathsTreesOD.sizePolicy().hasHeightForWidth())
        self.comboBoxCombPathsTreesOD.setSizePolicy(sizePolicy)
        self.comboBoxCombPathsTreesOD.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxCombPathsTreesOD.setObjectName(_fromUtf8("comboBoxCombPathsTreesOD"))
        self.comboBoxCombPathsTreesOD.addItem(_fromUtf8(""))
        self.comboBoxCombPathsTreesOD.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxCombPathsTreesOD, 0, 0, 3, 2)
        self.toolBoxPaths.addItem(self.page_3, _fromUtf8(""))
        self.layoutWidget2 = QtGui.QWidget(self.groupBoxPaths)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 60, 311, 22))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_29 = QtGui.QLabel(self.layoutWidget2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_13.addWidget(self.label_29)
        self.comboBoxCriterion = QtGui.QComboBox(self.layoutWidget2)
        self.comboBoxCriterion.setObjectName(_fromUtf8("comboBoxCriterion"))
        self.horizontalLayout_13.addWidget(self.comboBoxCriterion)
        self.groupBoxPathsParameters = QtGui.QGroupBox(self.tab_5)
        self.groupBoxPathsParameters.setEnabled(True)
        self.groupBoxPathsParameters.setGeometry(QtCore.QRect(360, 260, 271, 181))
        self.groupBoxPathsParameters.setObjectName(_fromUtf8("groupBoxPathsParameters"))
        self.layoutWidget_8 = QtGui.QWidget(self.groupBoxPathsParameters)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 30, 251, 111))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.gridLayout_13 = QtGui.QGridLayout(self.layoutWidget_8)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.doubleSpinBoxCyclingSpeed = QtGui.QDoubleSpinBox(self.layoutWidget_8)
        self.doubleSpinBoxCyclingSpeed.setProperty("value", 11.0)
        self.doubleSpinBoxCyclingSpeed.setObjectName(_fromUtf8("doubleSpinBoxCyclingSpeed"))
        self.gridLayout_13.addWidget(self.doubleSpinBoxCyclingSpeed, 3, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget_8)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_13.addWidget(self.label_14, 3, 3, 1, 1)
        self.doubleSpinBoxWalkingSpeed = QtGui.QDoubleSpinBox(self.layoutWidget_8)
        self.doubleSpinBoxWalkingSpeed.setProperty("value", 3.6)
        self.doubleSpinBoxWalkingSpeed.setObjectName(_fromUtf8("doubleSpinBoxWalkingSpeed"))
        self.gridLayout_13.addWidget(self.doubleSpinBoxWalkingSpeed, 2, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget_8)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_13.addWidget(self.label_13, 2, 3, 1, 1)
        self.labelTpsStatVelo = QtGui.QLabel(self.layoutWidget_8)
        self.labelTpsStatVelo.setObjectName(_fromUtf8("labelTpsStatVelo"))
        self.gridLayout_13.addWidget(self.labelTpsStatVelo, 3, 0, 1, 2)
        self.labelTpsStatVP = QtGui.QLabel(self.layoutWidget_8)
        self.labelTpsStatVP.setObjectName(_fromUtf8("labelTpsStatVP"))
        self.gridLayout_13.addWidget(self.labelTpsStatVP, 2, 0, 1, 2)
        self.label_16 = QtGui.QLabel(self.layoutWidget_8)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_13.addWidget(self.label_16, 1, 0, 1, 2)
        self.spinBoxSecurityTimeMin = QtGui.QSpinBox(self.layoutWidget_8)
        self.spinBoxSecurityTimeMin.setProperty("value", 10)
        self.spinBoxSecurityTimeMin.setObjectName(_fromUtf8("spinBoxSecurityTimeMin"))
        self.gridLayout_13.addWidget(self.spinBoxSecurityTimeMin, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget_8)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_13.addWidget(self.label, 1, 3, 1, 1)
        self.spinBoxMaxCost = QtGui.QSpinBox(self.layoutWidget_8)
        self.spinBoxMaxCost.setMaximum(600)
        self.spinBoxMaxCost.setProperty("value", 60)
        self.spinBoxMaxCost.setObjectName(_fromUtf8("spinBoxMaxCost"))
        self.gridLayout_13.addWidget(self.spinBoxMaxCost, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget_8)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_13.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget_8)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_13.addWidget(self.label_5, 0, 0, 1, 2)
        self.Tabs.addTab(self.tab_5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBoxForcStop = QtGui.QGroupBox(self.tab_2)
        self.groupBoxForcStop.setGeometry(QtCore.QRect(370, 360, 261, 71))
        self.groupBoxForcStop.setObjectName(_fromUtf8("groupBoxForcStop"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBoxForcStop)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 30, 241, 25))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.comboBoxForcStop = QtGui.QComboBox(self.layoutWidget3)
        self.comboBoxForcStop.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxForcStop.sizePolicy().hasHeightForWidth())
        self.comboBoxForcStop.setSizePolicy(sizePolicy)
        self.comboBoxForcStop.setObjectName(_fromUtf8("comboBoxForcStop"))
        self.horizontalLayout_7.addWidget(self.comboBoxForcStop)
        self.pushButtonChooseForcStopOnMap = QtGui.QPushButton(self.layoutWidget3)
        self.pushButtonChooseForcStopOnMap.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonChooseForcStopOnMap.sizePolicy().hasHeightForWidth())
        self.pushButtonChooseForcStopOnMap.setSizePolicy(sizePolicy)
        self.pushButtonChooseForcStopOnMap.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonChooseForcStopOnMap.setObjectName(_fromUtf8("pushButtonChooseForcStopOnMap"))
        self.horizontalLayout_7.addWidget(self.pushButtonChooseForcStopOnMap)
        self.groupBoxForcRoute = QtGui.QGroupBox(self.tab_2)
        self.groupBoxForcRoute.setGeometry(QtCore.QRect(10, 360, 341, 71))
        self.groupBoxForcRoute.setObjectName(_fromUtf8("groupBoxForcRoute"))
        self.comboBoxForcRoute = QtGui.QComboBox(self.groupBoxForcRoute)
        self.comboBoxForcRoute.setGeometry(QtCore.QRect(10, 30, 321, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxForcRoute.sizePolicy().hasHeightForWidth())
        self.comboBoxForcRoute.setSizePolicy(sizePolicy)
        self.comboBoxForcRoute.setObjectName(_fromUtf8("comboBoxForcRoute"))
        self.groupBoxGTFSFeeds = QtGui.QGroupBox(self.tab_2)
        self.groupBoxGTFSFeeds.setGeometry(QtCore.QRect(10, 10, 341, 121))
        self.groupBoxGTFSFeeds.setObjectName(_fromUtf8("groupBoxGTFSFeeds"))
        self.listViewGTFSFeeds = QtGui.QListView(self.groupBoxGTFSFeeds)
        self.listViewGTFSFeeds.setGeometry(QtCore.QRect(10, 40, 321, 71))
        self.listViewGTFSFeeds.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listViewGTFSFeeds.setAlternatingRowColors(True)
        self.listViewGTFSFeeds.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.listViewGTFSFeeds.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listViewGTFSFeeds.setObjectName(_fromUtf8("listViewGTFSFeeds"))
        self.groupBoxAgencies = QtGui.QGroupBox(self.tab_2)
        self.groupBoxAgencies.setGeometry(QtCore.QRect(10, 140, 341, 211))
        self.groupBoxAgencies.setObjectName(_fromUtf8("groupBoxAgencies"))
        self.tableViewAgencies = QtGui.QTableView(self.groupBoxAgencies)
        self.tableViewAgencies.setGeometry(QtCore.QRect(10, 40, 321, 161))
        self.tableViewAgencies.setAlternatingRowColors(True)
        self.tableViewAgencies.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableViewAgencies.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableViewAgencies.setObjectName(_fromUtf8("tableViewAgencies"))
        self.groupBoxTransportModes = QtGui.QGroupBox(self.tab_2)
        self.groupBoxTransportModes.setEnabled(True)
        self.groupBoxTransportModes.setGeometry(QtCore.QRect(370, 10, 261, 341))
        self.groupBoxTransportModes.setObjectName(_fromUtf8("groupBoxTransportModes"))
        self.layoutWidget_14 = QtGui.QWidget(self.groupBoxTransportModes)
        self.layoutWidget_14.setGeometry(QtCore.QRect(10, 40, 241, 131))
        self.layoutWidget_14.setObjectName(_fromUtf8("layoutWidget_14"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.layoutWidget_14)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.listViewIModes = QtGui.QListView(self.layoutWidget_14)
        self.listViewIModes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewIModes.setObjectName(_fromUtf8("listViewIModes"))
        self.horizontalLayout_3.addWidget(self.listViewIModes)
        self.layoutWidget_16 = QtGui.QWidget(self.groupBoxTransportModes)
        self.layoutWidget_16.setGeometry(QtCore.QRect(10, 180, 241, 141))
        self.layoutWidget_16.setObjectName(_fromUtf8("layoutWidget_16"))
        self.gridLayout_14 = QtGui.QGridLayout(self.layoutWidget_16)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_22 = QtGui.QLabel(self.layoutWidget_16)
        self.label_22.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_14.addWidget(self.label_22, 0, 0, 1, 1)
        self.listViewPTModes = QtGui.QListView(self.layoutWidget_16)
        self.listViewPTModes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewPTModes.setObjectName(_fromUtf8("listViewPTModes"))
        self.gridLayout_14.addWidget(self.listViewPTModes, 0, 1, 2, 1)
        self.label_23 = QtGui.QLabel(self.layoutWidget_16)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_14.addWidget(self.label_23, 1, 0, 1, 1)
        self.Tabs.addTab(self.tab_2, _fromUtf8(""))
        self.TabIndicateurs = QtGui.QWidget()
        self.TabIndicateurs.setObjectName(_fromUtf8("TabIndicateurs"))
        self.groupBoxDays = QtGui.QGroupBox(self.TabIndicateurs)
        self.groupBoxDays.setGeometry(QtCore.QRect(10, 10, 321, 361))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBoxDays.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxDays.setFont(font)
        self.groupBoxDays.setObjectName(_fromUtf8("groupBoxDays"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBoxDays)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 30, 291, 19))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButtonPreciseDate = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButtonPreciseDate.setChecked(True)
        self.radioButtonPreciseDate.setObjectName(_fromUtf8("radioButtonPreciseDate"))
        self.horizontalLayout_4.addWidget(self.radioButtonPreciseDate)
        self.radioButtonDayType = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButtonDayType.setObjectName(_fromUtf8("radioButtonDayType"))
        self.horizontalLayout_4.addWidget(self.radioButtonDayType)
        self.toolBoxDays = QtGui.QToolBox(self.groupBoxDays)
        self.toolBoxDays.setGeometry(QtCore.QRect(20, 60, 291, 281))
        self.toolBoxDays.setObjectName(_fromUtf8("toolBoxDays"))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 291, 227))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.calendarWidget = QtGui.QCalendarWidget(self.page_4)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 291, 221))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.toolBoxDays.addItem(self.page_4, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.layoutWidget_12 = QtGui.QWidget(self.page_5)
        self.layoutWidget_12.setGeometry(QtCore.QRect(0, 0, 291, 161))
        self.layoutWidget_12.setObjectName(_fromUtf8("layoutWidget_12"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget_12)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelLastDay = QtGui.QLabel(self.layoutWidget_12)
        self.labelLastDay.setEnabled(True)
        self.labelLastDay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelLastDay.setObjectName(_fromUtf8("labelLastDay"))
        self.gridLayout_3.addWidget(self.labelLastDay, 3, 0, 1, 1)
        self.comboBoxDayType = QtGui.QComboBox(self.layoutWidget_12)
        self.comboBoxDayType.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDayType.sizePolicy().hasHeightForWidth())
        self.comboBoxDayType.setSizePolicy(sizePolicy)
        self.comboBoxDayType.setObjectName(_fromUtf8("comboBoxDayType"))
        self.gridLayout_3.addWidget(self.comboBoxDayType, 0, 0, 1, 2)
        self.dateEditPerStart = QtGui.QDateEdit(self.layoutWidget_12)
        self.dateEditPerStart.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEditPerStart.sizePolicy().hasHeightForWidth())
        self.dateEditPerStart.setSizePolicy(sizePolicy)
        self.dateEditPerStart.setObjectName(_fromUtf8("dateEditPerStart"))
        self.gridLayout_3.addWidget(self.dateEditPerStart, 2, 1, 1, 1)
        self.comboBoxPerType = QtGui.QComboBox(self.layoutWidget_12)
        self.comboBoxPerType.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPerType.sizePolicy().hasHeightForWidth())
        self.comboBoxPerType.setSizePolicy(sizePolicy)
        self.comboBoxPerType.setObjectName(_fromUtf8("comboBoxPerType"))
        self.gridLayout_3.addWidget(self.comboBoxPerType, 1, 0, 1, 2)
        self.dateEditPerEnd = QtGui.QDateEdit(self.layoutWidget_12)
        self.dateEditPerEnd.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEditPerEnd.sizePolicy().hasHeightForWidth())
        self.dateEditPerEnd.setSizePolicy(sizePolicy)
        self.dateEditPerEnd.setObjectName(_fromUtf8("dateEditPerEnd"))
        self.gridLayout_3.addWidget(self.dateEditPerEnd, 3, 1, 1, 1)
        self.labelFirstDay = QtGui.QLabel(self.layoutWidget_12)
        self.labelFirstDay.setEnabled(True)
        self.labelFirstDay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFirstDay.setObjectName(_fromUtf8("labelFirstDay"))
        self.gridLayout_3.addWidget(self.labelFirstDay, 2, 0, 1, 1)
        self.comboBoxDayAg = QtGui.QComboBox(self.layoutWidget_12)
        self.comboBoxDayAg.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDayAg.sizePolicy().hasHeightForWidth())
        self.comboBoxDayAg.setSizePolicy(sizePolicy)
        self.comboBoxDayAg.setObjectName(_fromUtf8("comboBoxDayAg"))
        self.gridLayout_3.addWidget(self.comboBoxDayAg, 4, 1, 2, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget_12)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 2, 1)
        self.toolBoxDays.addItem(self.page_5, _fromUtf8(""))
        self.groupBoxTimePeriod = QtGui.QGroupBox(self.TabIndicateurs)
        self.groupBoxTimePeriod.setGeometry(QtCore.QRect(350, 10, 291, 361))
        self.groupBoxTimePeriod.setObjectName(_fromUtf8("groupBoxTimePeriod"))
        self.layoutWidget4 = QtGui.QWidget(self.groupBoxTimePeriod)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 271, 20))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.radioButtonTimePoint = QtGui.QRadioButton(self.layoutWidget4)
        self.radioButtonTimePoint.setEnabled(True)
        self.radioButtonTimePoint.setObjectName(_fromUtf8("radioButtonTimePoint"))
        self.horizontalLayout_10.addWidget(self.radioButtonTimePoint)
        self.radioButtonTimePeriod = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonTimePeriod.sizePolicy().hasHeightForWidth())
        self.radioButtonTimePeriod.setSizePolicy(sizePolicy)
        self.radioButtonTimePeriod.setChecked(False)
        self.radioButtonTimePeriod.setObjectName(_fromUtf8("radioButtonTimePeriod"))
        self.horizontalLayout_10.addWidget(self.radioButtonTimePeriod)
        self.toolBoxTime = QtGui.QToolBox(self.groupBoxTimePeriod)
        self.toolBoxTime.setEnabled(True)
        self.toolBoxTime.setGeometry(QtCore.QRect(10, 110, 271, 201))
        self.toolBoxTime.setObjectName(_fromUtf8("toolBoxTime"))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 271, 147))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.layoutWidget5 = QtGui.QWidget(self.page_6)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 10, 271, 22))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.labelTimeConstraint = QtGui.QLabel(self.layoutWidget5)
        self.labelTimeConstraint.setObjectName(_fromUtf8("labelTimeConstraint"))
        self.horizontalLayout_14.addWidget(self.labelTimeConstraint)
        self.timeEditTimePoint = QtGui.QTimeEdit(self.layoutWidget5)
        self.timeEditTimePoint.setEnabled(True)
        self.timeEditTimePoint.setTime(QtCore.QTime(8, 0, 0))
        self.timeEditTimePoint.setCalendarPopup(True)
        self.timeEditTimePoint.setObjectName(_fromUtf8("timeEditTimePoint"))
        self.horizontalLayout_14.addWidget(self.timeEditTimePoint)
        self.toolBoxTime.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 271, 147))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.layoutWidget6 = QtGui.QWidget(self.page_7)
        self.layoutWidget6.setGeometry(QtCore.QRect(0, 10, 271, 31))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget6)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.timeEditTimeEnd = QtGui.QTimeEdit(self.layoutWidget6)
        self.timeEditTimeEnd.setEnabled(True)
        self.timeEditTimeEnd.setTime(QtCore.QTime(23, 59, 0))
        self.timeEditTimeEnd.setCalendarPopup(True)
        self.timeEditTimeEnd.setObjectName(_fromUtf8("timeEditTimeEnd"))
        self.gridLayout_6.addWidget(self.timeEditTimeEnd, 0, 3, 1, 1)
        self.labelToTime = QtGui.QLabel(self.layoutWidget6)
        self.labelToTime.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelToTime.sizePolicy().hasHeightForWidth())
        self.labelToTime.setSizePolicy(sizePolicy)
        self.labelToTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelToTime.setObjectName(_fromUtf8("labelToTime"))
        self.gridLayout_6.addWidget(self.labelToTime, 0, 2, 1, 1)
        self.labelFromTime = QtGui.QLabel(self.layoutWidget6)
        self.labelFromTime.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFromTime.sizePolicy().hasHeightForWidth())
        self.labelFromTime.setSizePolicy(sizePolicy)
        self.labelFromTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFromTime.setObjectName(_fromUtf8("labelFromTime"))
        self.gridLayout_6.addWidget(self.labelFromTime, 0, 0, 1, 1)
        self.timeEditTimeStart = QtGui.QTimeEdit(self.layoutWidget6)
        self.timeEditTimeStart.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEditTimeStart.sizePolicy().hasHeightForWidth())
        self.timeEditTimeStart.setSizePolicy(sizePolicy)
        self.timeEditTimeStart.setTime(QtCore.QTime(0, 0, 0))
        self.timeEditTimeStart.setObjectName(_fromUtf8("timeEditTimeStart"))
        self.gridLayout_6.addWidget(self.timeEditTimeStart, 0, 1, 1, 1)
        self.layoutWidget7 = QtGui.QWidget(self.page_7)
        self.layoutWidget7.setGeometry(QtCore.QRect(0, 110, 271, 29))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_24 = QtGui.QLabel(self.layoutWidget7)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_5.addWidget(self.label_24)
        self.comboBoxTimeAg = QtGui.QComboBox(self.layoutWidget7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxTimeAg.sizePolicy().hasHeightForWidth())
        self.comboBoxTimeAg.setSizePolicy(sizePolicy)
        self.comboBoxTimeAg.setObjectName(_fromUtf8("comboBoxTimeAg"))
        self.horizontalLayout_5.addWidget(self.comboBoxTimeAg)
        self.layoutWidget8 = QtGui.QWidget(self.page_7)
        self.layoutWidget8.setGeometry(QtCore.QRect(0, 50, 271, 57))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.gridLayout_10 = QtGui.QGridLayout(self.layoutWidget8)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.radioButtonTimeInterval = QtGui.QRadioButton(self.layoutWidget8)
        self.radioButtonTimeInterval.setChecked(True)
        self.radioButtonTimeInterval.setObjectName(_fromUtf8("radioButtonTimeInterval"))
        self.gridLayout_10.addWidget(self.radioButtonTimeInterval, 0, 0, 1, 1)
        self.radioButtonAllServices = QtGui.QRadioButton(self.layoutWidget8)
        self.radioButtonAllServices.setObjectName(_fromUtf8("radioButtonAllServices"))
        self.gridLayout_10.addWidget(self.radioButtonAllServices, 1, 0, 1, 2)
        self.timeEditTimeInterval = QtGui.QTimeEdit(self.layoutWidget8)
        self.timeEditTimeInterval.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEditTimeInterval.sizePolicy().hasHeightForWidth())
        self.timeEditTimeInterval.setSizePolicy(sizePolicy)
        self.timeEditTimeInterval.setTime(QtCore.QTime(0, 30, 0))
        self.timeEditTimeInterval.setObjectName(_fromUtf8("timeEditTimeInterval"))
        self.gridLayout_10.addWidget(self.timeEditTimeInterval, 0, 1, 1, 1)
        self.toolBoxTime.addItem(self.page_7, _fromUtf8(""))
        self.layoutWidget9 = QtGui.QWidget(self.groupBoxTimePeriod)
        self.layoutWidget9.setGeometry(QtCore.QRect(10, 70, 271, 22))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_11 = QtGui.QLabel(self.layoutWidget9)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_8.addWidget(self.label_11)
        self.comboBoxTimeConstraint = QtGui.QComboBox(self.layoutWidget9)
        self.comboBoxTimeConstraint.setObjectName(_fromUtf8("comboBoxTimeConstraint"))
        self.comboBoxTimeConstraint.addItem(_fromUtf8(""))
        self.comboBoxTimeConstraint.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.comboBoxTimeConstraint)
        self.Tabs.addTab(self.TabIndicateurs, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBoxGeoQuery = QtGui.QGroupBox(self.tab)
        self.groupBoxGeoQuery.setGeometry(QtCore.QRect(10, 270, 631, 191))
        self.groupBoxGeoQuery.setObjectName(_fromUtf8("groupBoxGeoQuery"))
        self.groupBoxSize = QtGui.QGroupBox(self.groupBoxGeoQuery)
        self.groupBoxSize.setGeometry(QtCore.QRect(10, 20, 361, 161))
        self.groupBoxSize.setObjectName(_fromUtf8("groupBoxSize"))
        self.layoutWidget10 = QtGui.QWidget(self.groupBoxSize)
        self.layoutWidget10.setGeometry(QtCore.QRect(10, 30, 341, 122))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.gridLayout_11 = QtGui.QGridLayout(self.layoutWidget10)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButtonMapUnit = QtGui.QRadioButton(self.layoutWidget10)
        self.radioButtonMapUnit.setObjectName(_fromUtf8("radioButtonMapUnit"))
        self.verticalLayout.addWidget(self.radioButtonMapUnit)
        self.radioButtonScreenUnit = QtGui.QRadioButton(self.layoutWidget10)
        self.radioButtonScreenUnit.setChecked(True)
        self.radioButtonScreenUnit.setObjectName(_fromUtf8("radioButtonScreenUnit"))
        self.verticalLayout.addWidget(self.radioButtonScreenUnit)
        self.gridLayout_11.addLayout(self.verticalLayout, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget10)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_11.addWidget(self.label_10, 0, 0, 1, 1)
        self.comboBoxSizeIndic = QtGui.QComboBox(self.layoutWidget10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSizeIndic.sizePolicy().hasHeightForWidth())
        self.comboBoxSizeIndic.setSizePolicy(sizePolicy)
        self.comboBoxSizeIndic.setObjectName(_fromUtf8("comboBoxSizeIndic"))
        self.gridLayout_11.addWidget(self.comboBoxSizeIndic, 0, 1, 1, 2)
        self.doubleSpinBoxSize = QtGui.QDoubleSpinBox(self.layoutWidget10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxSize.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxSize.setSizePolicy(sizePolicy)
        self.doubleSpinBoxSize.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinBoxSize.setDecimals(0)
        self.doubleSpinBoxSize.setMaximum(1000000.0)
        self.doubleSpinBoxSize.setProperty("value", 20.0)
        self.doubleSpinBoxSize.setObjectName(_fromUtf8("doubleSpinBoxSize"))
        self.gridLayout_11.addWidget(self.doubleSpinBoxSize, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget10)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_11.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget10)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_11.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget10)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_11.addWidget(self.label_18, 1, 0, 1, 1)
        self.spinBoxSizeIndicMaxValue = QtGui.QSpinBox(self.layoutWidget10)
        self.spinBoxSizeIndicMaxValue.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBoxSizeIndicMaxValue.setMaximum(1000000)
        self.spinBoxSizeIndicMaxValue.setObjectName(_fromUtf8("spinBoxSizeIndicMaxValue"))
        self.gridLayout_11.addWidget(self.spinBoxSizeIndicMaxValue, 2, 1, 1, 1)
        self.spinBoxSizeIndicMinValue = QtGui.QSpinBox(self.layoutWidget10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxSizeIndicMinValue.sizePolicy().hasHeightForWidth())
        self.spinBoxSizeIndicMinValue.setSizePolicy(sizePolicy)
        self.spinBoxSizeIndicMinValue.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBoxSizeIndicMinValue.setMaximum(1000000)
        self.spinBoxSizeIndicMinValue.setObjectName(_fromUtf8("spinBoxSizeIndicMinValue"))
        self.gridLayout_11.addWidget(self.spinBoxSizeIndicMinValue, 1, 1, 1, 1)
        self.groupBoxColor = QtGui.QGroupBox(self.groupBoxGeoQuery)
        self.groupBoxColor.setGeometry(QtCore.QRect(390, 20, 231, 161))
        self.groupBoxColor.setObjectName(_fromUtf8("groupBoxColor"))
        self.layoutWidget_9 = QtGui.QWidget(self.groupBoxColor)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 30, 211, 81))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget_9)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_9)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_9.addWidget(self.label_6, 0, 0, 1, 1)
        self.comboBoxColorIndic = QtGui.QComboBox(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxColorIndic.sizePolicy().hasHeightForWidth())
        self.comboBoxColorIndic.setSizePolicy(sizePolicy)
        self.comboBoxColorIndic.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxColorIndic.setObjectName(_fromUtf8("comboBoxColorIndic"))
        self.gridLayout_9.addWidget(self.comboBoxColorIndic, 0, 1, 1, 2)
        self.label_21 = QtGui.QLabel(self.layoutWidget_9)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_9.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget_9)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_9.addWidget(self.label_20, 2, 0, 1, 1)
        self.spinBoxColorIndicMaxValue = QtGui.QSpinBox(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxColorIndicMaxValue.sizePolicy().hasHeightForWidth())
        self.spinBoxColorIndicMaxValue.setSizePolicy(sizePolicy)
        self.spinBoxColorIndicMaxValue.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spinBoxColorIndicMaxValue.setMaximum(1000000)
        self.spinBoxColorIndicMaxValue.setObjectName(_fromUtf8("spinBoxColorIndicMaxValue"))
        self.gridLayout_9.addWidget(self.spinBoxColorIndicMaxValue, 2, 1, 1, 2)
        self.spinBoxColorIndicMinValue = QtGui.QSpinBox(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxColorIndicMinValue.sizePolicy().hasHeightForWidth())
        self.spinBoxColorIndicMinValue.setSizePolicy(sizePolicy)
        self.spinBoxColorIndicMinValue.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spinBoxColorIndicMinValue.setMaximum(1000000)
        self.spinBoxColorIndicMinValue.setObjectName(_fromUtf8("spinBoxColorIndicMinValue"))
        self.gridLayout_9.addWidget(self.spinBoxColorIndicMinValue, 1, 1, 1, 2)
        self.toolBoxDisplay = QtGui.QToolBox(self.tab)
        self.toolBoxDisplay.setGeometry(QtCore.QRect(10, 10, 631, 241))
        self.toolBoxDisplay.setObjectName(_fromUtf8("toolBoxDisplay"))
        self.page_8 = QtGui.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 631, 187))
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.layoutWidget11 = QtGui.QWidget(self.page_8)
        self.layoutWidget11.setGeometry(QtCore.QRect(20, 0, 601, 31))
        self.layoutWidget11.setObjectName(_fromUtf8("layoutWidget11"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget11)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.labelReq = QtGui.QLabel(self.layoutWidget11)
        self.labelReq.setEnabled(True)
        self.labelReq.setObjectName(_fromUtf8("labelReq"))
        self.horizontalLayout_11.addWidget(self.labelReq)
        self.comboBoxReq = QtGui.QComboBox(self.layoutWidget11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxReq.sizePolicy().hasHeightForWidth())
        self.comboBoxReq.setSizePolicy(sizePolicy)
        self.comboBoxReq.setEditable(True)
        self.comboBoxReq.setObjectName(_fromUtf8("comboBoxReq"))
        self.horizontalLayout_11.addWidget(self.comboBoxReq)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.pushButtonReqRename = QtGui.QPushButton(self.layoutWidget11)
        self.pushButtonReqRename.setObjectName(_fromUtf8("pushButtonReqRename"))
        self.horizontalLayout_11.addWidget(self.pushButtonReqRename)
        self.pushButtonReqDelete = QtGui.QPushButton(self.layoutWidget11)
        self.pushButtonReqDelete.setEnabled(True)
        self.pushButtonReqDelete.setObjectName(_fromUtf8("pushButtonReqDelete"))
        self.horizontalLayout_11.addWidget(self.pushButtonReqDelete)
        self.layoutWidget12 = QtGui.QWidget(self.page_8)
        self.layoutWidget12.setGeometry(QtCore.QRect(20, 40, 601, 73))
        self.layoutWidget12.setObjectName(_fromUtf8("layoutWidget12"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_17 = QtGui.QLabel(self.layoutWidget12)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        self.textEditComments = QtGui.QTextEdit(self.layoutWidget12)
        self.textEditComments.setObjectName(_fromUtf8("textEditComments"))
        self.horizontalLayout_12.addWidget(self.textEditComments)
        self.pushButtonSaveComments = QtGui.QPushButton(self.layoutWidget12)
        self.pushButtonSaveComments.setObjectName(_fromUtf8("pushButtonSaveComments"))
        self.horizontalLayout_12.addWidget(self.pushButtonSaveComments)
        self.toolBoxDisplay.addItem(self.page_8, _fromUtf8(""))
        self.page_9 = QtGui.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 631, 187))
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.layoutWidget_7 = QtGui.QWidget(self.page_9)
        self.layoutWidget_7.setGeometry(QtCore.QRect(20, 0, 601, 31))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.labelDerivedIndic = QtGui.QLabel(self.layoutWidget_7)
        self.labelDerivedIndic.setEnabled(True)
        self.labelDerivedIndic.setObjectName(_fromUtf8("labelDerivedIndic"))
        self.horizontalLayout_15.addWidget(self.labelDerivedIndic)
        self.comboBoxDerivedRep = QtGui.QComboBox(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDerivedRep.sizePolicy().hasHeightForWidth())
        self.comboBoxDerivedRep.setSizePolicy(sizePolicy)
        self.comboBoxDerivedRep.setEditable(True)
        self.comboBoxDerivedRep.setObjectName(_fromUtf8("comboBoxDerivedRep"))
        self.horizontalLayout_15.addWidget(self.comboBoxDerivedRep)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.pushButtonDerivedRepRename = QtGui.QPushButton(self.layoutWidget_7)
        self.pushButtonDerivedRepRename.setObjectName(_fromUtf8("pushButtonDerivedRepRename"))
        self.horizontalLayout_15.addWidget(self.pushButtonDerivedRepRename)
        self.pushButtonDerivedRepDelete = QtGui.QPushButton(self.layoutWidget_7)
        self.pushButtonDerivedRepDelete.setEnabled(True)
        self.pushButtonDerivedRepDelete.setObjectName(_fromUtf8("pushButtonDerivedRepDelete"))
        self.horizontalLayout_15.addWidget(self.pushButtonDerivedRepDelete)
        self.groupBoxParamDerivedRep = QtGui.QGroupBox(self.page_9)
        self.groupBoxParamDerivedRep.setGeometry(QtCore.QRect(10, 40, 611, 131))
        self.groupBoxParamDerivedRep.setObjectName(_fromUtf8("groupBoxParamDerivedRep"))
        self.layoutWidget_6 = QtGui.QWidget(self.groupBoxParamDerivedRep)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 20, 591, 96))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.gridLayout_12 = QtGui.QGridLayout(self.layoutWidget_6)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.doubleSpinBoxRepParam = QtGui.QDoubleSpinBox(self.layoutWidget_6)
        self.doubleSpinBoxRepParam.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinBoxRepParam.setDecimals(3)
        self.doubleSpinBoxRepParam.setProperty("value", 0.0)
        self.doubleSpinBoxRepParam.setObjectName(_fromUtf8("doubleSpinBoxRepParam"))
        self.gridLayout_12.addWidget(self.doubleSpinBoxRepParam, 2, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget_6)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_12.addWidget(self.label_12, 0, 3, 1, 1)
        self.spinBoxDerivedRepClasses = QtGui.QSpinBox(self.layoutWidget_6)
        self.spinBoxDerivedRepClasses.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBoxDerivedRepClasses.setMaximum(999)
        self.spinBoxDerivedRepClasses.setProperty("value", 20)
        self.spinBoxDerivedRepClasses.setObjectName(_fromUtf8("spinBoxDerivedRepClasses"))
        self.gridLayout_12.addWidget(self.spinBoxDerivedRepClasses, 0, 4, 1, 1)
        self.spinBoxDerivedRepIndicMaxValue = QtGui.QSpinBox(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxDerivedRepIndicMaxValue.sizePolicy().hasHeightForWidth())
        self.spinBoxDerivedRepIndicMaxValue.setSizePolicy(sizePolicy)
        self.spinBoxDerivedRepIndicMaxValue.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBoxDerivedRepIndicMaxValue.setMaximum(1000000)
        self.spinBoxDerivedRepIndicMaxValue.setObjectName(_fromUtf8("spinBoxDerivedRepIndicMaxValue"))
        self.gridLayout_12.addWidget(self.spinBoxDerivedRepIndicMaxValue, 2, 1, 1, 1)
        self.comboBoxDerivedRepIndic = QtGui.QComboBox(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDerivedRepIndic.sizePolicy().hasHeightForWidth())
        self.comboBoxDerivedRepIndic.setSizePolicy(sizePolicy)
        self.comboBoxDerivedRepIndic.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxDerivedRepIndic.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBoxDerivedRepIndic.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxDerivedRepIndic.setObjectName(_fromUtf8("comboBoxDerivedRepIndic"))
        self.gridLayout_12.addWidget(self.comboBoxDerivedRepIndic, 0, 1, 1, 2)
        self.label_25 = QtGui.QLabel(self.layoutWidget_6)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_12.addWidget(self.label_25, 1, 3, 1, 1)
        self.pushButtonDerivedRepGenerate = QtGui.QPushButton(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDerivedRepGenerate.sizePolicy().hasHeightForWidth())
        self.pushButtonDerivedRepGenerate.setSizePolicy(sizePolicy)
        self.pushButtonDerivedRepGenerate.setBaseSize(QtCore.QSize(100, 0))
        self.pushButtonDerivedRepGenerate.setObjectName(_fromUtf8("pushButtonDerivedRepGenerate"))
        self.gridLayout_12.addWidget(self.pushButtonDerivedRepGenerate, 1, 5, 1, 1)
        self.spinBoxDerivedRepIndicMinValue = QtGui.QSpinBox(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxDerivedRepIndicMinValue.sizePolicy().hasHeightForWidth())
        self.spinBoxDerivedRepIndicMinValue.setSizePolicy(sizePolicy)
        self.spinBoxDerivedRepIndicMinValue.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBoxDerivedRepIndicMinValue.setMaximum(1000000)
        self.spinBoxDerivedRepIndicMinValue.setObjectName(_fromUtf8("spinBoxDerivedRepIndicMinValue"))
        self.gridLayout_12.addWidget(self.spinBoxDerivedRepIndicMinValue, 1, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.layoutWidget_6)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_12.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.layoutWidget_6)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_12.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget_6)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_12.addWidget(self.label_26, 2, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_12.addWidget(self.label_15, 0, 0, 1, 1)
        self.comboBoxRepMeth = QtGui.QComboBox(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxRepMeth.sizePolicy().hasHeightForWidth())
        self.comboBoxRepMeth.setSizePolicy(sizePolicy)
        self.comboBoxRepMeth.setObjectName(_fromUtf8("comboBoxRepMeth"))
        self.gridLayout_12.addWidget(self.comboBoxRepMeth, 1, 4, 1, 1)
        self.toolBoxDisplay.addItem(self.page_9, _fromUtf8(""))
        self.layoutWidget_4 = QtGui.QWidget(self.tab)
        self.layoutWidget_4.setGeometry(QtCore.QRect(30, 480, 591, 29))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBoxPathID = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBoxPathID.setMaximumSize(QtCore.QSize(60, 16777215))
        self.comboBoxPathID.setObjectName(_fromUtf8("comboBoxPathID"))
        self.horizontalLayout_2.addWidget(self.comboBoxPathID)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pushButtonReqDisplay = QtGui.QPushButton(self.layoutWidget_4)
        self.pushButtonReqDisplay.setEnabled(True)
        self.pushButtonReqDisplay.setObjectName(_fromUtf8("pushButtonReqDisplay"))
        self.horizontalLayout_2.addWidget(self.pushButtonReqDisplay)
        self.Tabs.addTab(self.tab, _fromUtf8(""))
        self.layoutWidget13 = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget13.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget13.setObjectName(_fromUtf8("layoutWidget13"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_23.setMargin(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.layoutWidget14 = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget14.setGeometry(QtCore.QRect(10, 560, 641, 31))
        self.layoutWidget14.setObjectName(_fromUtf8("layoutWidget14"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget14)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButtonReinitCalc = QtGui.QPushButton(self.layoutWidget14)
        self.pushButtonReinitCalc.setObjectName(_fromUtf8("pushButtonReinitCalc"))
        self.gridLayout_5.addWidget(self.pushButtonReinitCalc, 0, 0, 1, 1)
        self.labelElapsedTime = QtGui.QLabel(self.layoutWidget14)
        self.labelElapsedTime.setText(_fromUtf8(""))
        self.labelElapsedTime.setObjectName(_fromUtf8("labelElapsedTime"))
        self.gridLayout_5.addWidget(self.labelElapsedTime, 0, 1, 1, 1)
        self.checkBoxVerbose = QtGui.QCheckBox(self.layoutWidget14)
        self.checkBoxVerbose.setObjectName(_fromUtf8("checkBoxVerbose"))
        self.gridLayout_5.addWidget(self.checkBoxVerbose, 0, 3, 1, 1)
        self.pushButtonIndicCalculate = QtGui.QPushButton(self.layoutWidget14)
        self.pushButtonIndicCalculate.setObjectName(_fromUtf8("pushButtonIndicCalculate"))
        self.gridLayout_5.addWidget(self.pushButtonIndicCalculate, 0, 2, 1, 1)
        TempusAccessDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(TempusAccessDockWidget)
        self.Tabs.setCurrentIndex(0)
        self.toolBoxPaths.setCurrentIndex(2)
        self.toolBoxDays.setCurrentIndex(0)
        self.toolBoxTime.setCurrentIndex(1)
        self.toolBoxDisplay.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TempusAccessDockWidget)

    def retranslateUi(self, TempusAccessDockWidget):
        TempusAccessDockWidget.setWindowTitle(_translate("TempusAccessDockWidget", "Analyse de l\'offre de transport", None))
        self.groupBoxObjType.setTitle(_translate("TempusAccessDockWidget", "Types d\'objets", None))
        self.comboBoxObjType.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>Type d\'objet unitaire pour le calcul de la requête</p></body></html>", None))
        self.groupBoxPerimetre.setTitle(_translate("TempusAccessDockWidget", "Restreindre à une zone", None))
        self.labelPerimeterType.setText(_translate("TempusAccessDockWidget", "Type de périmètre", None))
        self.labelPerimeter.setText(_translate("TempusAccessDockWidget", "Périmètre", None))
        self.groupBoxIndicators.setTitle(_translate("TempusAccessDockWidget", "Indicateurs", None))
        self.groupBoxPaths.setTitle(_translate("TempusAccessDockWidget", "Paramétrage des itinéraires et arborescences", None))
        self.label_33.setText(_translate("TempusAccessDockWidget", "Type de noeuds O et D", None))
        self.labelFromNode.setText(_translate("TempusAccessDockWidget", "O", None))
        self.pushButtonChooseOrigOnMap.setText(_translate("TempusAccessDockWidget", "+", None))
        self.labelToNode.setText(_translate("TempusAccessDockWidget", "D", None))
        self.pushButtonChooseDestOnMap.setText(_translate("TempusAccessDockWidget", "+", None))
        self.pushButtonInvertOD.setText(_translate("TempusAccessDockWidget", "O <-> D", None))
        self.toolBoxPaths.setItemText(self.toolBoxPaths.indexOf(self.page), _translate("TempusAccessDockWidget", "Itinéraires O-D", None))
        self.comboBoxPathsTreeOD.setItemText(0, _translate("TempusAccessDockWidget", "Origine", None))
        self.comboBoxPathsTreeOD.setItemText(1, _translate("TempusAccessDockWidget", "Destination", None))
        self.pushButtonChoosePathsTreeRootOnMap.setText(_translate("TempusAccessDockWidget", "+", None))
        self.toolBoxPaths.setItemText(self.toolBoxPaths.indexOf(self.page_2), _translate("TempusAccessDockWidget", "Arborescence O-* ou *-D", None))
        self.pushButtonRemovePathsTreesRoots.setText(_translate("TempusAccessDockWidget", "-", None))
        self.pushButtonChoosePathsTreesRootsOnMap.setText(_translate("TempusAccessDockWidget", "+", None))
        self.label_9.setText(_translate("TempusAccessDockWidget", "Méthode d\'agrégation", None))
        self.comboBoxCombPathsTreesOD.setItemText(0, _translate("TempusAccessDockWidget", "Origine(s)", None))
        self.comboBoxCombPathsTreesOD.setItemText(1, _translate("TempusAccessDockWidget", "Destination(s)", None))
        self.toolBoxPaths.setItemText(self.toolBoxPaths.indexOf(self.page_3), _translate("TempusAccessDockWidget", "Combinaison d\'arborescences", None))
        self.label_29.setText(_translate("TempusAccessDockWidget", "Critère d\'optimisation", None))
        self.groupBoxPathsParameters.setTitle(_translate("TempusAccessDockWidget", "Paramétrage des arborescences", None))
        self.label_14.setText(_translate("TempusAccessDockWidget", "km/h", None))
        self.label_13.setText(_translate("TempusAccessDockWidget", "km/h", None))
        self.labelTpsStatVelo.setText(_translate("TempusAccessDockWidget", "Vitesse vélo", None))
        self.labelTpsStatVP.setText(_translate("TempusAccessDockWidget", "Vitesse marche", None))
        self.label_16.setText(_translate("TempusAccessDockWidget", "Temps de sécurité TC", None))
        self.label.setText(_translate("TempusAccessDockWidget", "minutes", None))
        self.label_7.setText(_translate("TempusAccessDockWidget", "minutes", None))
        self.label_5.setText(_translate("TempusAccessDockWidget", "Valeur maximum", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_5), _translate("TempusAccessDockWidget", "Objets", None))
        self.groupBoxForcStop.setTitle(_translate("TempusAccessDockWidget", "Obliger le passage par un arrêt", None))
        self.pushButtonChooseForcStopOnMap.setText(_translate("TempusAccessDockWidget", "+", None))
        self.groupBoxForcRoute.setTitle(_translate("TempusAccessDockWidget", "Obliger la desserte par une ligne", None))
        self.groupBoxGTFSFeeds.setTitle(_translate("TempusAccessDockWidget", "Sélectionner la source de données GTFS", None))
        self.groupBoxAgencies.setTitle(_translate("TempusAccessDockWidget", "Sélectionner les transporteurs", None))
        self.groupBoxTransportModes.setTitle(_translate("TempusAccessDockWidget", "Sélectionner les modes de transport", None))
        self.label_2.setText(_translate("TempusAccessDockWidget", "Individuels", None))
        self.label_22.setText(_translate("TempusAccessDockWidget", "Transport", None))
        self.label_23.setText(_translate("TempusAccessDockWidget", "collectif", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("TempusAccessDockWidget", "Réseaux et modes", None))
        self.groupBoxDays.setTitle(_translate("TempusAccessDockWidget", "Paramétrage des jours", None))
        self.radioButtonPreciseDate.setText(_translate("TempusAccessDockWidget", "Date précise", None))
        self.radioButtonDayType.setText(_translate("TempusAccessDockWidget", "Type de jour", None))
        self.toolBoxDays.setItemText(self.toolBoxDays.indexOf(self.page_4), _translate("TempusAccessDockWidget", "Date précise", None))
        self.labelLastDay.setText(_translate("TempusAccessDockWidget", "Fin période", None))
        self.labelFirstDay.setText(_translate("TempusAccessDockWidget", "Début période", None))
        self.label_8.setText(_translate("TempusAccessDockWidget", "Méthode d\'agrégation", None))
        self.toolBoxDays.setItemText(self.toolBoxDays.indexOf(self.page_5), _translate("TempusAccessDockWidget", "Type de jour", None))
        self.groupBoxTimePeriod.setTitle(_translate("TempusAccessDockWidget", "Paramétrage des horaires", None))
        self.radioButtonTimePoint.setText(_translate("TempusAccessDockWidget", "A une heure précise", None))
        self.radioButtonTimePeriod.setText(_translate("TempusAccessDockWidget", "Sur une période horaire", None))
        self.labelTimeConstraint.setText(_translate("TempusAccessDockWidget", "Partir après...", None))
        self.toolBoxTime.setItemText(self.toolBoxTime.indexOf(self.page_6), _translate("TempusAccessDockWidget", "Heure précise", None))
        self.labelToTime.setText(_translate("TempusAccessDockWidget", "et", None))
        self.labelFromTime.setText(_translate("TempusAccessDockWidget", "Départ entre", None))
        self.label_24.setText(_translate("TempusAccessDockWidget", "Méthode d\'agrégation", None))
        self.radioButtonTimeInterval.setText(_translate("TempusAccessDockWidget", "Toutes les", None))
        self.radioButtonAllServices.setText(_translate("TempusAccessDockWidget", "Chercher tous les services de la période", None))
        self.toolBoxTime.setItemText(self.toolBoxTime.indexOf(self.page_7), _translate("TempusAccessDockWidget", "Période horaire", None))
        self.label_11.setText(_translate("TempusAccessDockWidget", "Type de contrainte horaire", None))
        self.comboBoxTimeConstraint.setItemText(0, _translate("TempusAccessDockWidget", "Sur l\'heure de départ", None))
        self.comboBoxTimeConstraint.setItemText(1, _translate("TempusAccessDockWidget", "Sur l\'heure d\'arrivée", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.TabIndicateurs), _translate("TempusAccessDockWidget", "Jours et heures", None))
        self.groupBoxGeoQuery.setTitle(_translate("TempusAccessDockWidget", "Style d\'affichage des objets", None))
        self.groupBoxSize.setTitle(_translate("TempusAccessDockWidget", "Taille", None))
        self.radioButtonMapUnit.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>&quot;Unité de la carte&quot; implique une définition de la taille de l\'indicateur en mètres. La taille du symbole le représentant sera d\'autant plus importante que le zoom est fort. </p></body></html>", None))
        self.radioButtonMapUnit.setText(_translate("TempusAccessDockWidget", "Unité de la carte (m)", None))
        self.radioButtonScreenUnit.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>&quot;Unité de la carte&quot; implique une définition de la taille de l\'indicateur en millimètres. La taille du symbole le représentant sera stable à tous les niveaux de zoom. Pour des zooms très faibles, une faible lisibilité est possible en raison de superposition des symboles. </p></body></html>", None))
        self.radioButtonScreenUnit.setText(_translate("TempusAccessDockWidget", "Unité de l\'écran (mm)", None))
        self.label_10.setText(_translate("TempusAccessDockWidget", "Indicateur", None))
        self.comboBoxSizeIndic.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>Choisir l\'indicateur à cartographier par des variations de taille des symboles</p></body></html>", None))
        self.label_3.setText(_translate("TempusAccessDockWidget", "Taille max ", None))
        self.label_19.setText(_translate("TempusAccessDockWidget", "Valeur associée à la taille max", None))
        self.label_18.setText(_translate("TempusAccessDockWidget", "Valeur associée à la taille 0", None))
        self.groupBoxColor.setTitle(_translate("TempusAccessDockWidget", "Dégradé de couleurs", None))
        self.label_6.setText(_translate("TempusAccessDockWidget", "Indicateur", None))
        self.comboBoxColorIndic.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>Choisir l\'indicateur à cartographier par des variations de couleurs des symboles</p></body></html>", None))
        self.label_21.setText(_translate("TempusAccessDockWidget", "Valeur min", None))
        self.label_20.setText(_translate("TempusAccessDockWidget", "Valeur max", None))
        self.labelReq.setText(_translate("TempusAccessDockWidget", "Couches", None))
        self.pushButtonReqRename.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>Renommer la requête dans la base de données</p></body></html>", None))
        self.pushButtonReqRename.setText(_translate("TempusAccessDockWidget", "Renommer", None))
        self.pushButtonReqDelete.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>Supprimer la requête stockée de la base de donnée (opération non-annulable)</p></body></html>", None))
        self.pushButtonReqDelete.setText(_translate("TempusAccessDockWidget", "Supprimer", None))
        self.label_17.setText(_translate("TempusAccessDockWidget", "Commentaires", None))
        self.pushButtonSaveComments.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>Sauvegarder les commentaires de la requête dans la base de données</p></body></html>", None))
        self.pushButtonSaveComments.setText(_translate("TempusAccessDockWidget", "Enregistrer", None))
        self.toolBoxDisplay.setItemText(self.toolBoxDisplay.indexOf(self.page_8), _translate("TempusAccessDockWidget", "Requêtes stockées", None))
        self.labelDerivedIndic.setText(_translate("TempusAccessDockWidget", "Couches", None))
        self.pushButtonDerivedRepRename.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>Renommer la requête dans la base de données</p></body></html>", None))
        self.pushButtonDerivedRepRename.setText(_translate("TempusAccessDockWidget", "Renommer", None))
        self.pushButtonDerivedRepDelete.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>Supprimer la requête stockée de la base de donnée (opération non-annulable)</p></body></html>", None))
        self.pushButtonDerivedRepDelete.setText(_translate("TempusAccessDockWidget", "Supprimer", None))
        self.groupBoxParamDerivedRep.setTitle(_translate("TempusAccessDockWidget", "Paramètres de génération d\'une isosurface", None))
        self.label_12.setText(_translate("TempusAccessDockWidget", "Nombre de classes", None))
        self.comboBoxDerivedRepIndic.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>Choisir l\'indicateur à cartographier par des variations de couleurs des symboles</p></body></html>", None))
        self.label_25.setText(_translate("TempusAccessDockWidget", "Méthode", None))
        self.pushButtonDerivedRepGenerate.setText(_translate("TempusAccessDockWidget", "Générer", None))
        self.label_28.setText(_translate("TempusAccessDockWidget", "Valeur max", None))
        self.label_27.setText(_translate("TempusAccessDockWidget", "Valeur min", None))
        self.label_26.setText(_translate("TempusAccessDockWidget", "Paramètre", None))
        self.label_15.setText(_translate("TempusAccessDockWidget", "Indicateur", None))
        self.toolBoxDisplay.setItemText(self.toolBoxDisplay.indexOf(self.page_9), _translate("TempusAccessDockWidget", "Isosurfaces dérivées de la requête stockée courante", None))
        self.label_4.setText(_translate("TempusAccessDockWidget", "Filtrer les chemins : afficher l\'identifiant", None))
        self.pushButtonReqDisplay.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>Cartographier les indicateurs choisis</p></body></html>", None))
        self.pushButtonReqDisplay.setText(_translate("TempusAccessDockWidget", "Ajouter la couche", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("TempusAccessDockWidget", "Affichage", None))
        self.pushButtonReinitCalc.setText(_translate("TempusAccessDockWidget", "Nouveau calcul", None))
        self.checkBoxVerbose.setToolTip(_translate("TempusAccessDockWidget", "<html><head/><body><p>Si activé, les opérations de chargement de données et les requêtes de calcul d\'indicateurs exécutées seront tracées dans le fichier &quot;log.txt&quot; du plugin.Utiliser pour le debugage ou pour récupérer les requêtes et les transformer en script si nécessaire. </p></body></html>", None))
        self.checkBoxVerbose.setText(_translate("TempusAccessDockWidget", "Ecrire dans le log", None))
        self.pushButtonIndicCalculate.setText(_translate("TempusAccessDockWidget", "Calculer", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TempusAccessDockWidget = QtGui.QDockWidget()
    ui = Ui_TempusAccessDockWidget()
    ui.setupUi(TempusAccessDockWidget)
    TempusAccessDockWidget.show()
    sys.exit(app.exec_())

